// 专有名词 / 术语表数据
// 结构: [w 英文, c 中文, s 例句, cat 分类, ipa 音标(可选)]
// 分类: 身体词 / 肢体功能 / 解剖方位 / 海洋 / 海峡 / 海湾 / 大陆 / 美国州名 / 海洋生物 / 叙述方式 / 灭绝事件 / 地质年代 / 写景词 / 历史运动
const PROPER_NOUNS = [
  ["nose", "鼻子（日常词；学术词 nasal）", "They've got thick hair all over their body, even on their noses. （来源：TPO49-L5 驯鹿的适应）", "身体词", "/noʊz/"],
  ["nasal", "鼻的（学术词；日常词 nose）", "So, how do the dolphin's clicks get transmitted from its air-filled nasal sacs into the ocean water? （来源：TPO23-L5 海豚的导航）", "身体词", "/ˈneɪ.zəl/"],
  ["nasal sacs", "鼻囊：既可指人的鼻腔，也可指海豚的鼻腔（后者的结构更复杂）", "These sounds, it's been found, are produced in the air-filled nasal sacs of the dolphin. （来源：TPO23-L5 海豚的导航）", "身体词", ""],
  ["mouth", "口，嘴（日常词；学术词 oral）；河口", "Pretty weird-looking, huh? And another thing—the tube worm has no mouth or digestive organs! （来源：TPO15-L3 关于生物群落的新发现）", "身体词", "/maʊθ/"],
  ["oral", "口的（学术词；日常词 mouth）", "Traditionally, folktales were passed down orally, from storyteller to storyteller, for, since ancient times. （来源：TPO20-L5 民间故事）", "身体词", "/ˈɔːr.əl/"],
  ["ear", "耳朵（日常词；学术词 aural / otic）", "The ear area of the skull had characteristics seen only in aquatic mammals, specifically whales. （来源：TPO10-L2 鲸鱼的进化史）", "身体词", "/ɪr/"],
  ["aural", "耳的，听觉的（学术词；日常词 ear）", "The lecture on dolphin echolocation concentrated on the aural system that allows the animals to sense objects underwater. （来源：词典风格）", "身体词", "/ˈɔːr.əl/"],
  ["otic", "耳的（更专业的医学用词）", "The otic region of the skull houses the delicate organs of hearing and balance. （来源：词典风格）", "身体词", "/ˈoʊ.tɪk/"],
  ["tooth", "牙齿（日常词；学术词 dental）", "For a long time, we assumed that all whales that had teeth, including sperm whales and killer whales, were closely related to one another. （来源：TPO10-L2 鲸鱼的进化史）", "身体词", "/tuːθ/"],
  ["dental", "牙齿的（学术词；日常词 tooth）", "Dental enamel is the hardest substance in the human body, yet it can be eroded by acidic foods over time. （来源：词典风格）", "身体词", "/ˈden.t̬əl/"],
  ["heart", "心脏（日常词；学术词 cardiac）", "When a whale dives, its metabolic rate drops, causing its heartbeat to slow down. （来源：TPO25-L4 讨论鲸的呼吸）", "身体词", "/hɑːrt/"],
  ["cardiac", "心脏的（学术词；日常词 heart）", "Cardiac muscle contracts rhythmically throughout life without any conscious effort on our part. （来源：词典风格）", "身体词", "/ˈkɑːr.di.æk/"],
  ["lung", "肺（日常词；学术词 pulmonary）", "The bones found in the graves show a layer of soot on the inside of the ribs, and people's lungs would have been coated with the same black soot. （来源：TPO1-L5 农业遗址卡塔胡亚克）", "身体词", "/lʌŋ/"],
  ["pulmonary", "肺的（学术词；日常词 lung）", "Pulmonary arteries carry deoxygenated blood from the heart to the lungs, where it picks up fresh oxygen. （来源：词典风格）", "身体词", "/ˈpʊl.mə.ner.i/"],
  ["liver", "肝脏（日常词；学术词 hepatic）", "So the middle part of the frog, its internal organs—its heart, lungs, liver—these start getting drier and drier. （来源：TPO18-L6 北美林蛙）", "身体词", "/ˈlɪv.ər/"],
  ["hepatic", "肝脏的（学术词；日常词 liver）", "Hepatic cells are responsible for filtering toxins from the blood and processing the nutrients absorbed from the intestine. （来源：词典风格）", "身体词", "/hɪˈpæt̬.ɪk/"],
  ["Pacific Ocean", "太平洋（世界上面积最大、最深的大洋）", "The volcanoes in the Hawaiian Islands, in the Pacific Ocean, are shield volcanoes; they're formed over a hot spot of magma. （来源：TPO24-L6 金星上的盾火山）", "海洋", "/pəˈsɪf.ɪk ˈoʊ.ʃən/"],
  ["Atlantic Ocean", "大西洋（世界第二大洋，形状呈 S 形）", "For those of you who don't know the northeast coastal region, Cape Cod is a peninsula, a narrow strip of land that jets out into the Atlantic. （来源：TPO11-L3 “海角”式房屋）", "海洋", "/ətˈlæn.tɪk ˈoʊ.ʃən/"],
  ["Indian Ocean", "印度洋（世界第三大洋，大部分位于南半球）", "The Indian Ocean is the third largest of the world's five oceans, with most of its waters lying south of the equator. （来源：词典风格）", "海洋", "/ˈɪn.di.ən ˈoʊ.ʃən/"],
  ["Arctic Ocean", "北冰洋（面积最小、最浅的大洋，位于北极地区）", "The Arctic Ocean is the smallest and shallowest of the world's oceans, and much of its surface is covered with sea ice for most of the year. （来源：词典风格）", "海洋", "/ˈɑːrk.tɪk ˈoʊ.ʃən/"],
  ["Southern Ocean", "南大洋（2000 年划定的新大洋，环绕南极洲）", "The Southern Ocean encircles the continent of Antarctica and connects the Atlantic, Pacific, and Indian Oceans. （来源：词典风格）", "海洋", "/ˈsʌð.ərn ˈoʊ.ʃən/"],
  ["Mediterranean Sea", "地中海（位于欧、亚、非三洲之间）", "The Antikythera Mechanism was found a hundred years ago, underwater in an ancient Greek shipwreck in the Mediterranean Sea. （来源：TPO23-L2 安提凯西亚装置）", "海洋", "/ˌmed.ɪ.təˈreɪ.ni.ən ˈsiː/"],
  ["Red Sea", "红海（位于非洲和阿拉伯半岛之间）", "The Red Sea lies between Africa and the Arabian Peninsula and is famous for its rich coral reefs. （来源：词典风格）", "海洋", "/red siː/"],
  ["Black Sea", "黑海（位于欧洲和亚洲之间）", "The Black Sea is an inland sea lying between southeastern Europe and Asia Minor, connected to the Mediterranean by the Bosporus. （来源：词典风格）", "海洋", "/blæk siː/"],
  ["Caspian Sea", "里海（世界上最大的内陆湖，常被称为“海”）", "The Caspian Sea is actually the largest inland body of water in the world, though it is commonly referred to as a sea. （来源：词典风格）", "海洋", "/ˈkæs.pi.ən ˈsiː/"],
  ["Baltic Sea", "波罗的海（位于北欧）", "The Baltic Sea is a shallow, almost landlocked sea in northern Europe, bordered by Scandinavia and the Baltic states. （来源：词典风格）", "海洋", "/ˈbɔːl.tɪk ˈsiː/"],
  ["North Sea", "北海（位于大西洋东北部，欧洲西北岸）", "The North Sea lies between Great Britain and northwestern Europe and has long been an important source of fish and, more recently, petroleum. （来源：词典风格）", "海洋", "/nɔːrθ siː/"],
  ["Caribbean Sea", "加勒比海（位于大西洋西部，美洲中部）", "The Caribbean Sea is bounded by the islands of the West Indies and the coasts of Central and South America. （来源：词典风格）", "海洋", "/ˌkær.ɪˈbiː.ən ˈsiː/"],
  ["Arabian Sea", "阿拉伯海（位于印度洋西北部）", "The Arabian Sea, forming the northwestern part of the Indian Ocean, receives the waters of the Indus River. （来源：词典风格）", "海洋", "/əˈreɪ.bi.ən ˈsiː/"],
  ["South China Sea", "南中国海（位于太平洋西部）", "The South China Sea is one of the busiest shipping routes in the world, connecting the Pacific and Indian Oceans. （来源：词典风格）", "海洋", "/saʊθ ˈtʃaɪ.nə siː/"],
  ["Strait of Gibraltar", "直布罗陀海峡（连接地中海与大西洋）", "The Strait of Gibraltar, a narrow passage only about fourteen kilometers wide, links the Mediterranean Sea with the Atlantic Ocean. （来源：词典风格）", "海峡", "/streɪt əv dʒɪˈbrɔːl.tər/"],
  ["Strait of Malacca", "马六甲海峡（连接印度洋与太平洋 / 南海）", "The Strait of Malacca, lying between the Malay Peninsula and Sumatra, is one of the most heavily traveled sea lanes in the world. （来源：词典风格）", "海峡", "/streɪt əv məˈlæk.ə/"],
  ["English Channel", "英吉利海峡（连接大西洋与北海）", "The English Channel separates the south coast of England from the north coast of France, and it is one of the busiest shipping lanes in the world. （来源：词典风格）", "海峡", "/ˈɪŋ.ɡlɪʃ ˈtʃæn.əl/"],
  ["Bering Strait", "白令海峡（连接北冰洋与太平洋）", "The Bering Strait, which separates Asia from North America, is only about eighty-five kilometers wide at its narrowest point. （来源：词典风格）", "海峡", "/ˈber.ɪŋ streɪt/"],
  ["Strait of Hormuz", "霍尔木兹海峡（连接波斯湾与印度洋）", "The Strait of Hormuz connects the Persian Gulf with the Gulf of Oman, and a large share of the world's oil passes through it. （来源：词典风格）", "海峡", "/streɪt əv hɔːrˈmuːz/"],
  ["Gulf of Mexico", "墨西哥湾（位于北美洲东南部）", "I mean, as it flies all the way across the Gulf of Mexico, it uses up almost none of its body fat. （来源：TPO3-L2 蜂鸟）", "海湾", "/ɡʌlf əv ˈmek.sɪ.koʊ/"],
  ["Persian Gulf", "波斯湾（位于西亚，石油资源丰富）", "The Persian Gulf is a shallow arm of the Indian Ocean bordered by oil-rich states such as Saudi Arabia, Iran, and Kuwait. （来源：词典风格）", "海湾", "/ˈpɜːr.ʒən ɡʌlf/"],
  ["Gulf of Guinea", "几内亚湾（位于西非）", "The Gulf of Guinea is the part of the Atlantic Ocean that indents the west coast of Africa. （来源：词典风格）", "海湾", "/ɡʌlf əv ˈɡɪn.i/"],
  ["Gulf of Alaska", "阿拉斯加湾（位于北美洲西北部）", "The Gulf of Alaska, a large curved arm of the Pacific Ocean, is known for its rough seas and abundant fisheries. （来源：词典风格）", "海湾", "/ɡʌlf əv əˈlæs.kə/"],
  ["Bay of Bengal", "孟加拉湾（世界上最大的海湾）", "The Bay of Bengal, the largest bay in the world, is bordered by India, Bangladesh, and Myanmar. （来源：词典风格）", "海湾", "/beɪ əv beŋˈɡɔːl/"],
  ["Antarctica", "南极洲", "But we recently noticed an increase in cloud cover over an area of the ocean waters around Antarctica—an increased area of low, thick clouds. （来源：TPO23-L3 地球热平衡）", "大陆", "/ænˈtɑːrk.tɪ.kə/"],
  ["Oceania", "大洋洲", "Oceania is the collective name for the thousands of islands scattered across the central and southern Pacific Ocean, including Australia and New Zealand. （来源：词典风格）", "大陆", "/ˌoʊ.ʃiˈæn.i.ə/"],
  ["microscopic marine plants", "微型海洋植物（浮游植物，海洋食物链的基础）", "Well, the reason for this increased cloud cover, it turns out, is the exceptionally large amount of microscopic marine plants. （来源：TPO23-L3 地球热平衡）", "海洋生物", "/ˌmaɪ.krəˈskɑː.pɪk məˈriːn plænts/"],
  ["microorganisms", "微生物", "What they discovered was that microorganisms—bacteria—had taken over both functions of the biological community: the recycling of waste materials and the production of energy. （来源：TPO15-L3 关于生物群落的新发现）", "海洋生物", "/ˌmaɪ.kroʊˈɔːr.ɡə.nɪz.əmz/"],
  ["chronological order", "顺叙（事件按实际发生顺序讲述：1→2→3→4）", "But “Araby” is easier because it's linear; the story unfolds chronologically. （来源：TPO23-L4 选课建议）", "叙述方式", "/ˌkrɒn.əˈlɒdʒ.ɪ.kəl ˈɔːr.dər/"],
  ["flashback", "倒叙（从中间或结局开始，再回头讲之前的事：3→1→2→4）", "In many novels the author opens with a flashback, showing a key scene from the past before returning to the present action. （来源：词典风格）", "叙述方式", "/ˈflæʃ.bæk/"],
  ["in medias res", "插叙 / 从故事中途开始（非线性的叙述方式）", "Epic poems frequently begin in medias res, dropping the reader directly into the middle of the action. （来源：词典风格）", "叙述方式", "/ɪn ˌmeɪ.di.æs ˈreɪs/"],
  ["non-linear", "非线性的（中间穿插过去和未来的叙述方式）", "A non-linear narrative, which jumps freely between past and present, is common in modern filmmaking. （来源：词典风格）", "叙述方式", "/nɑːn ˈlɪn.i.ər/"],
  ["Ordovician-Silurian extinction", "奥陶纪-志留纪灭绝事件", "The Ordovician-Silurian extinction, which occurred roughly 443 million years ago, eliminated a large percentage of marine species. （来源：词典风格）", "灭绝事件", "/ˌɔːr.dəˈvɪʃ.ən sɪˈlʊr.i.ən ɪkˈstɪŋk.ʃən/"],
  ["Late Devonian extinction", "晚泥盆世灭绝事件", "The Late Devonian extinction struck mainly at marine organisms, particularly the reef-building corals of the period. （来源：词典风格）", "灭绝事件", "/leɪt dɪˈvoʊ.ni.ən ɪkˈstɪŋk.ʃən/"],
  ["Permian-Triassic extinction", "二叠纪-三叠纪灭绝事件（也称“大死亡” The Great Dying）", "The Permian-Triassic extinction, often called the Great Dying, was the most severe extinction event in Earth's history, wiping out about 95 percent of marine species. （来源：词典风格）", "灭绝事件", "/ˈpɜːr.mi.ən traɪˈæs.ɪk ɪkˈstɪŋk.ʃən/"],
  ["The Great Dying", "“大死亡”（二叠纪-三叠纪灭绝事件的别称）", "The Great Dying is the popular name for the Permian-Triassic extinction, the largest mass extinction ever recorded in the fossil record. （来源：词典风格）", "灭绝事件", "/ðə ɡreɪt ˈdaɪ.ɪŋ/"],
  ["Triassic-Jurassic extinction", "三叠纪-侏罗纪灭绝事件", "The Triassic-Jurassic extinction removed many of the competitors of the early dinosaurs, clearing the way for them to dominate the land. （来源：词典风格）", "灭绝事件", "/traɪˈæs.ɪk dʒʊˈræs.ɪk ɪkˈstɪŋk.ʃən/"],
  ["Cretaceous-Paleogene extinction", "白垩纪-古近纪灭绝事件（恐龙灭绝的那次，简称 K-Pg）", "The Cretaceous-Paleogene extinction event, which killed off the dinosaurs 65 million years ago, is the most famous of the great mass extinctions. （来源：词典风格）", "灭绝事件", "/krɪˈteɪ.ʃəs ˈpæl.i.ə.dʒiːn ɪkˈstɪŋk.ʃən/"],
  ["Ordovician", "奥陶纪", "Trilobites and other marine invertebrates flourished in the warm shallow seas of the Ordovician period. （来源：词典风格）", "地质年代", "/ˌɔːr.dəˈvɪʃ.ən/"],
  ["Devonian", "泥盆纪", "During the Devonian period, often called the Age of Fishes, fish diversified into a remarkable variety of forms. （来源：词典风格）", "地质年代", "/dɪˈvoʊ.ni.ən/"],
  ["Permian", "二叠纪", "The Permian period ended with the largest mass extinction in Earth's history, when most marine and many terrestrial species vanished. （来源：词典风格）", "地质年代", "/ˈpɜːr.mi.ən/"],
  ["Triassic", "三叠纪", "The first dinosaurs appeared during the Triassic period, when the continents were still joined in a single landmass. （来源：词典风格）", "地质年代", "/traɪˈæs.ɪk/"],
  ["Cretaceous", "白垩纪", "Flowering plants spread widely during the Cretaceous period, providing new food sources for insects and dinosaurs alike. （来源：词典风格）", "地质年代", "/krɪˈteɪ.ʃəs/"],
  ["morning light", "晨光（下面例句出自一段山巅写景）", "The morning light spread gently across the open mountain top, touching the stone marker, the low shrubs, and the far ridges beyond. （来源：词典风格）", "写景词", ""],
  ["cairn", "石堆，石冢（用于标记路径或山顶）", "A small stacked cairn marked the summit of the mountain, where hikers left stones to show the way. （来源：词典风格）", "写景词", "/kern/"],
  ["ridge", "山脊，山岭", "So, during the second rainy period, the dunes were kind of chopped up at the top, full of hollows and ridges, and these hollows would've captured the rain right there on the top. （来源：TPO9-L5 沙漠湖泊形成的假说）", "写景词", "/rɪdʒ/"],
  ["shrub", "灌木", "And, scientists have noticed that there's been a change in surface vegetation during this time—shrubs are increasing in the tundra. （来源：TPO9-L3 苔原地的灌木丛）", "写景词", "/ʃrʌb/"],
  ["hind feet", "后足（动物后腿的脚部，hind foot 的复数）", "Kangaroos move by bounding along on their powerful hind feet, using their long tails for balance. （来源：词典风格）", "身体词", "/haɪnd fiːt/"],
  ["forelimb", "前肢（包括前腿、翅膀、鳍）", "In bats, the forelimb is modified into a wing, with the fingers elongated to support a thin membrane of skin. （来源：词典风格）", "身体词", "/ˈfɔːr.lɪm/"],
  ["hind limb", "后肢（比 hind feet 更学术的说法）", "The fossil showed four limbs that could have been used for walking, with the hind limbs considerably longer than the front ones. （来源：词典风格）", "身体词", "/haɪnd lɪm/"],
  ["pectoral fin", "胸鳍（鱼前部的鳍）", "Fish use their paired pectoral fins to steer, brake, and make sharp turns in the water. （来源：词典风格）", "身体词", "/ˈpek.tər.əl fɪn/"],
  ["pelvic fin", "腹鳍（鱼后部的鳍）", "The pelvic fins, located farther back on the body, help stabilize a fish as it swims and maneuver around obstacles. （来源：词典风格）", "身体词", "/ˈpel.vɪk fɪn/"],
  ["mandible", "下颌骨（下颚；jaw 的学术版）", "The mandible is the lower jawbone, the largest and strongest bone of the face. （来源：词典风格）", "身体词", "/ˈmæn.dɪ.bəl/"],
  ["maxilla", "上颌骨（与 mandible 相对）", "The maxilla, or upper jaw, holds the upper teeth and forms part of the floor of the eye socket. （来源：词典风格）", "身体词", "/mækˈsɪl.ə/"],
  ["appendage", "附肢（腿、触角、尾巴等身体附属结构）", "Insects use their antennae and other appendages to sense and explore their environment. （来源：词典风格）", "身体词", "/əˈpen.dɪdʒ/"],
  ["cranium", "颅骨（包住脑子的部分，不是整个头骨）", "The cranium is the part of the skull that encloses and protects the brain. （来源：词典风格）", "身体词", "/ˈkreɪ.ni.əm/"],
  ["pectoral", "胸部的；胸鳍的（动物学中特指胸部结构）", "Pectoral muscles, which attach the forelimbs to the body, are especially powerful in birds and bats. （来源：词典风格）", "身体词", "/ˈpek.tər.əl/"],
  ["pedal", "足的，足部的（如 pedal appendage = 足部附肢）", "The pedal appendages of the crab are adapted for walking across the seafloor. （来源：词典风格）", "身体词", "/ˈped.əl/"],
  ["grasp", "抓握，牢牢抓住（比 hold 更正式）", "Monkeys use their hands and feet to grasp branches firmly as they move through the trees. （来源：词典风格）", "肢体功能", "/ɡræsp/"],
  ["manipulate", "灵巧地操控（用手或口器处理物体）", "Then, in the editing room, you can digitally manipulate these images. （来源：TPO23-L6 屏幕舞蹈）", "肢体功能", "/məˈnɪp.jə.leɪt/"],
  ["bite force", "咬合力", "The bite force of a crocodile is powerful enough to crush the shells of turtles and the bones of large prey. （来源：词典风格）", "肢体功能", "/baɪt fɔːrs/"],
  ["mastication", "咀嚼（比 chewing 更学术的说法）", "Mastication, or chewing, breaks food into smaller pieces so that it can be swallowed and digested more easily. （来源：词典风格）", "肢体功能", "/ˌmæs.tɪˈkeɪ.ʃən/"],
  ["prehensile", "能缠绕抓握的（如猴子的尾巴）", "New World monkeys have a prehensile tail that can grip branches almost as effectively as a fifth hand. （来源：词典风格）", "肢体功能", "/prɪˈhen.səl/"],
  ["locomotion", "运动，移动方式（行走、游泳、飞翔等）", "Locomotion on land requires limbs strong enough to support the body weight, unlike swimming, where buoyancy helps. （来源：词典风格）", "肢体功能", "/ˌloʊ.kəˈmoʊ.ʃən/"],
  ["anterior", "前面的，靠前的（对应 posterior）", "The anterior part of the fish's body contains the head, with the gills lying just behind the eyes. （来源：词典风格）", "解剖方位", "/ænˈtɪr.i.ər/"],
  ["posterior", "后面的，靠后的（对应 anterior）", "The posterior legs of a grasshopper are much longer than the front legs, enabling it to leap great distances. （来源：词典风格）", "解剖方位", "/pɑːˈstɪr.i.ər/"],
  ["ventral", "腹侧的（肚子那一面；对应 dorsal）", "In most fish, the ventral surface is lighter in color than the dorsal surface, an adaptation that conceals them from predators. （来源：词典风格）", "解剖方位", "/ˈven.trəl/"],
  ["dorsal", "背侧的（背部那一面；对应 ventral）", "The dorsal fin of a shark rises above the water when the animal swims near the surface. （来源：词典风格）", "解剖方位", "/ˈdɔːr.səl/"],
  ["proximal", "近端的（靠近身体中心；对应 distal）", "The humerus is the proximal bone of the arm, since it lies closest to the shoulder. （来源：词典风格）", "解剖方位", "/ˈprɑːk.sɪ.məl/"],
  ["distal", "远端的（远离身体中心；对应 proximal）", "The fingers are the most distal parts of the arm, farthest from the shoulder and elbow. （来源：词典风格）", "解剖方位", "/ˈdɪs.təl/"],
  ["Alabama", "阿拉巴马州（美国东南部，绰号“黄锤州”Yellowhammer State）", "Alabama lies in the southeastern United States, where the aerospace industry is centered in Huntsville. （来源：词典风格）", "美国州名", "/ˌæl.əˈbæm.ə/"],
  ["State of Alabama", "阿拉巴马州（Alabama 的官方全称形式，正式文书与新闻中常见）", "The State of Alabama is nicknamed the Yellowhammer State, after the state bird. （来源：词典风格）", "美国州名", "/steɪt əv ˌæl.əˈbæm.ə/"],
  ["Alaska", "阿拉斯加州（美国面积最大的州，位于北美西北端）", "Alaska is fascinating to geologists because of its incredible landscapes. （来源：TPO49-L2 阿拉斯加的地质条件）", "美国州名", "/əˈlæs.kə/"],
  ["State of Alaska", "阿拉斯加州（Alaska 的官方全称形式）", "The State of Alaska is the largest state in the United States by area, yet one of the least densely populated. （来源：词典风格）", "美国州名", "/steɪt əv əˈlæs.kə/"],
  ["Arizona", "亚利桑那州（美国西南部，大峡谷所在地，气候干旱）", "Arizona is famous for the Grand Canyon and its dry desert climate. （来源：词典风格）", "美国州名", "/ˌer.ɪˈzoʊ.nə/"],
  ["State of Arizona", "亚利桑那州（Arizona 的官方全称形式）", "The State of Arizona experiences extremely hot summers in its desert regions. （来源：词典风格）", "美国州名", "/steɪt əv ˌer.ɪˈzoʊ.nə/"],
  ["Arkansas", "阿肯色州（美国南部，农业州，盛产大米与棉花）", "Arkansas is a southern state whose economy has long depended on agriculture, especially rice and cotton. （来源：词典风格）", "美国州名", "/ˈɑːr.kən.sɔː/"],
  ["State of Arkansas", "阿肯色州（Arkansas 的官方全称形式）", "The State of Arkansas has the only diamond mine in the country that is open to the public. （来源：词典风格）", "美国州名", "/steɪt əv ˈɑːr.kən.sɔː/"],
  ["California", "加利福尼亚州（美国人口最多的州，硅谷与好莱坞所在地）", "And there's a Clovis site in a valley in Southern California where the remains of thirteen mammoths were found. （来源：TPO24-L5 北美的巨型动物）", "美国州名", "/ˌkæl.ɪˈfɔːr.njə/"],
  ["State of California", "加利福尼亚州（California 的官方全称形式）", "The State of California produces a large share of the country's fruits and vegetables, thanks to its mild climate and fertile soil. （来源：词典风格）", "美国州名", "/steɪt əv ˌkæl.ɪˈfɔːr.njə/"],
  ["Colorado", "科罗拉多州（美国西部，落基山脉横贯，滑雪胜地）", "Colorado is a mountainous western state where skiing and tourism are major industries. （来源：词典风格）", "美国州名", "/ˌkɑːl.əˈræd.oʊ/"],
  ["State of Colorado", "科罗拉多州（Colorado 的官方全称形式）", "The State of Colorado is home to the Rocky Mountains, which attract millions of visitors every year. （来源：词典风格）", "美国州名", "/steɪt əv ˌkɑːl.əˈræd.oʊ/"],
  ["Connecticut", "康涅狄格州（美国东北部新英格兰地区，面积较小的州）", "Connecticut is one of the smallest states in the country, located in the New England region of the northeastern United States. （来源：词典风格）", "美国州名", "/kəˈnet.ɪ.kət/"],
  ["State of Connecticut", "康涅狄格州（Connecticut 的官方全称形式）", "The State of Connecticut has a long maritime history along the Atlantic coast. （来源：词典风格）", "美国州名", "/steɪt əv kəˈnet.ɪ.kət/"],
  ["Delaware", "特拉华州（美国面积第二小的州，第一个加入联邦）", "And this federation expanded from what's now southern Canada all the way south to Delaware River. （来源：TPO7-L5 易罗魁人和桦树）", "美国州名", "/ˈdel.ə.wer/"],
  ["State of Delaware", "特拉华州（Delaware 的官方全称形式）", "Delaware was the first state to ratify the Constitution, and the State of Delaware is now a popular place for companies to register because of its business-friendly laws. （来源：词典风格）", "美国州名", "/steɪt əv ˈdel.ə.wer/"],
  ["Florida", "佛罗里达州（美国东南部半岛，伸入大西洋与墨西哥湾之间）", "Florida has long had a great citrus industry—large growth of oranges, lemons, and the like. （来源：TPO11-L5 地形与气候）", "美国州名", "/ˈflɔːr.ɪ.də/"],
  ["State of Florida", "佛罗里达州（Florida 的官方全称形式）", "The State of Florida is a major producer of oranges and other citrus fruits in the United States. （来源：词典风格）", "美国州名", "/steɪt əv ˈflɔːr.ɪ.də/"],
  ["Georgia", "佐治亚州（美国东南部，首府亚特兰大，绰号“桃州”）", "Georgia is located in the southeastern United States, with Atlanta as its largest city. （来源：词典风格）", "美国州名", "/ˈdʒɔːr.dʒə/"],
  ["State of Georgia", "佐治亚州（Georgia 的官方全称形式）", "The State of Georgia is nicknamed the Peach State because of its many peach orchards. （来源：词典风格）", "美国州名", "/steɪt əv ˈdʒɔːr.dʒə/"],
  ["Hawaii", "夏威夷州（太平洋中部的火山群岛，美国唯一的群岛州）", "Long before the development of advanced navigational tools in Europe, Pacific islanders were travelling from New Zealand to Hawaii and back again, using nothing but the stars as their navigational instruments. （来源：TPO14-L5 古航海家对星象的利用）", "美国州名", "/həˈwaɪ.i/"],
  ["State of Hawaii", "夏威夷州（Hawaii 的官方全称形式）", "The State of Hawaii is the only state made entirely of islands, a chain of volcanic islands in the middle of the Pacific Ocean. （来源：词典风格）", "美国州名", "/steɪt əv həˈwaɪ.i/"],
  ["Idaho", "爱达荷州（美国西北部，土豆产量居全国第一）", "Idaho produces more potatoes than any other state in the country. （来源：词典风格）", "美国州名", "/ˈaɪ.də.hoʊ/"],
  ["State of Idaho", "爱达荷州（Idaho 的官方全称形式）", "The State of Idaho is known for its mountains, rivers, and vast potato farms. （来源：词典风格）", "美国州名", "/steɪt əv ˈaɪ.də.hoʊ/"],
  ["Illinois", "伊利诺伊州（美国中西部，最大城市芝加哥滨临密歇根湖）", "Illinois is a Midwestern state whose largest city, Chicago, lies on the shore of Lake Michigan. （来源：词典风格）", "美国州名", "/ˌɪl.ɪˈnɔɪ/"],
  ["State of Illinois", "伊利诺伊州（Illinois 的官方全称形式）", "The State of Illinois is a major transportation hub because of its central location in the country. （来源：词典风格）", "美国州名", "/steɪt əv ˌɪl.ɪˈnɔɪ/"],
  ["Indiana", "印第安纳州（美国中西部，农业发达，印第安纳波利斯500赛车闻名）", "Indiana is a Midwestern state with a strong agricultural economy and a long tradition of auto racing. （来源：词典风格）", "美国州名", "/ˌɪn.diˈæn.ə/"],
  ["State of Indiana", "印第安纳州（Indiana 的官方全称形式）", "The State of Indiana hosts the famous Indianapolis 500 automobile race every year. （来源：词典风格）", "美国州名", "/steɪt əv ˌɪn.diˈæn.ə/"],
  ["Iowa", "艾奥瓦州（美国中西部，玉米与大豆主产区）", "Oh, and speaking about farms, that reminds me—one interesting thing I read about Frantzen is that when she first moved back to Iowa after living abroad, she often visited this place in her town called the Sales Barn. （来源：TPO1-L2 画家弗兰森）", "美国州名", "/ˈaɪ.ə.wə/"],
  ["State of Iowa", "艾奥瓦州（Iowa 的官方全称形式）", "The State of Iowa is one of the leading producers of corn and soybeans in the nation. （来源：词典风格）", "美国州名", "/steɪt əv ˈaɪ.ə.wə/"],
  ["Kansas", "堪萨斯州（美国中部大平原，小麦主产区，绰号“向日葵州”）", "Kansas lies in the middle of the Great Plains, where wheat fields stretch for miles in every direction. （来源：词典风格）", "美国州名", "/ˈkæn.zəs/"],
  ["State of Kansas", "堪萨斯州（Kansas 的官方全称形式）", "The State of Kansas is a major producer of wheat in the United States. （来源：词典风格）", "美国州名", "/steɪt əv ˈkæn.zəs/"],
  ["Kentucky", "肯塔基州（美国南部，肯塔基德比赛马与波本威士忌闻名）", "And I think a good example is the pedestrian mall in the Louisville Kentucky, for instance. （来源：TPO13-L2 步行街的考虑要素）", "美国州名", "/kənˈtʌk.i/"],
  ["State of Kentucky", "肯塔基州（Kentucky 的官方全称形式）", "The State of Kentucky is famous for the Kentucky Derby and its bourbon whiskey industry. （来源：词典风格）", "美国州名", "/steɪt əv kənˈtʌk.i/"],
  ["Louisiana", "路易斯安那州（美国南部，新奥尔良是爵士乐发源地）", "Louisiana is known for New Orleans, the birthplace of jazz music. （来源：词典风格）", "美国州名", "/luːˌiː.ziˈæn.ə/"],
  ["State of Louisiana", "路易斯安那州（Louisiana 的官方全称形式）", "The State of Louisiana is bordered by the Mississippi River and the Gulf of Mexico. （来源：词典风格）", "美国州名", "/steɪt əv luːˌiː.ziˈæn.ə/"],
  ["Maine", "缅因州（美国最东端的州，海岸线曲折，盛产龙虾）", "And in adapting to extreme climates—like Maine in the wintertime—animals can evolve in pretty interesting ways. （来源：TPO20-L6 雪兔）", "美国州名", "/meɪn/"],
  ["State of Maine", "缅因州（Maine 的官方全称形式）", "The State of Maine is the largest producer of lobsters in the country, thanks to its rocky coastline. （来源：词典风格）", "美国州名", "/steɪt əv meɪn/"],
  ["Maryland", "马里兰州（美国大西洋沿岸，切萨皮克湾蓝蟹闻名）", "Maryland lies on the Atlantic coast, surrounding the large Chesapeake Bay. （来源：词典风格）", "美国州名", "/ˈmer.ɪ.lənd/"],
  ["State of Maryland", "马里兰州（Maryland 的官方全称形式）", "The State of Maryland is famous for the blue crabs caught in Chesapeake Bay. （来源：词典风格）", "美国州名", "/steɪt əv ˈmer.ɪ.lənd/"],
  ["Massachusetts", "马萨诸塞州（美国新英格兰地区，波士顿与哈佛、MIT 所在地）", "So for a long time the Massachusetts scientists tried to create a coating that acted like these lotus leaves—a coating that was superhydrophobic. （来源：TPO44-L2 纳米技术的应用）", "美国州名", "/ˌmæs.əˈtʃuː.sɪts/"],
  ["State of Massachusetts", "马萨诸塞州（Massachusetts 的官方全称形式）", "The State of Massachusetts is home to Boston and to some of the most famous universities in the world. （来源：词典风格）", "美国州名", "/steɪt əv ˌmæs.əˈtʃuː.sɪts/"],
  ["Michigan", "密歇根州（美国五大湖地区，汽车工业中心底特律所在地）", "Michigan is surrounded by the Great Lakes and is the center of the American automobile industry. （来源：词典风格）", "美国州名", "/ˈmɪʃ.ɪ.ɡən/"],
  ["State of Michigan", "密歇根州（Michigan 的官方全称形式）", "The State of Michigan is divided into an upper and a lower peninsula, separated by the Straits of Mackinac. （来源：词典风格）", "美国州名", "/steɪt əv ˈmɪʃ.ɪ.ɡən/"],
  ["Minnesota", "明尼苏达州（美国中北部，绰号“万湖之州”）", "Minnesota is known as the Land of 10,000 Lakes because of its many lakes. （来源：词典风格）", "美国州名", "/ˌmɪn.ɪˈsoʊ.t̬ə/"],
  ["State of Minnesota", "明尼苏达州（Minnesota 的官方全称形式）", "The State of Minnesota has more than ten thousand lakes within its borders. （来源：词典风格）", "美国州名", "/steɪt əv ˌmɪn.ɪˈsoʊ.t̬ə/"],
  ["Mississippi", "密西西比州（美国东南部，得名于密西西比河，蓝调音乐发源地）", "Mississippi is named after the Mississippi River, the longest river in the United States. （来源：词典风格）", "美国州名", "/ˌmɪs.ɪˈsɪp.i/"],
  ["State of Mississippi", "密西西比州（Mississippi 的官方全称形式）", "The State of Mississippi is considered the birthplace of the blues. （来源：词典风格）", "美国州名", "/steɪt əv ˌmɪs.ɪˈsɪp.i/"],
  ["Missouri", "密苏里州（美国中部，密苏里河与密西西比河在此交汇）", "Missouri lies at the meeting point of the Missouri and Mississippi Rivers. （来源：词典风格）", "美国州名", "/mɪˈzʊr.i/"],
  ["State of Missouri", "密苏里州（Missouri 的官方全称形式）", "The State of Missouri is known as the Gateway to the West. （来源：词典风格）", "美国州名", "/steɪt əv mɪˈzʊr.i/"],
  ["Montana", "蒙大拿州（美国西北部，黄石国家公园的一部分位于境内）", "Montana is a large western state with vast open plains and part of Yellowstone National Park. （来源：词典风格）", "美国州名", "/mɑːnˈtæn.ə/"],
  ["State of Montana", "蒙大拿州（Montana 的官方全称形式）", "The State of Montana is nicknamed Big Sky Country for its wide-open spaces. （来源：词典风格）", "美国州名", "/steɪt əv mɑːnˈtæn.ə/"],
  ["Nebraska", "内布拉斯加州（美国中部大平原，玉米主产区）", "Nebraska is an agricultural state in the middle of the Great Plains, with corn as its leading crop. （来源：词典风格）", "美国州名", "/nəˈbræs.kə/"],
  ["State of Nebraska", "内布拉斯加州（Nebraska 的官方全称形式）", "The State of Nebraska is one of the leading producers of corn in the nation. （来源：词典风格）", "美国州名", "/steɪt əv nəˈbræs.kə/"],
  ["Nevada", "内华达州（美国西部沙漠州，拉斯维加斯赌城闻名）", "Um, however, in the late 1980s, some scientists were exploring Devils Hole, which is basically an extensive, water-filled cave, far from the ocean in Nevada in the western United States. （来源：TPO17-L3 米兰科维奇假说）", "美国州名", "/nəˈvæd.ə/"],
  ["State of Nevada", "内华达州（Nevada 的官方全称形式）", "The State of Nevada was once a major center of silver and gold mining, and Las Vegas now draws millions of visitors. （来源：词典风格）", "美国州名", "/steɪt əv nəˈvæd.ə/"],
  ["New Hampshire", "新罕布什尔州（美国新英格兰地区，总统初选第一州）", "New Hampshire is a small New England state that holds the first presidential primary in the nation. （来源：词典风格）", "美国州名", "/nuː ˈhæmp.ʃər/"],
  ["State of New Hampshire", "新罕布什尔州（New Hampshire 的官方全称形式）", "The State of New Hampshire is nicknamed the Granite State because of its rocky mountains. （来源：词典风格）", "美国州名", "/steɪt əv nuː ˈhæmp.ʃər/"],
  ["New Jersey", "新泽西州（美国人口密度最高的州之一，位于纽约市旁）", "New Jersey is one of the most densely populated states in the country, lying next to New York City. （来源：词典风格）", "美国州名", "/nuː ˈdʒɜːr.zi/"],
  ["State of New Jersey", "新泽西州（New Jersey 的官方全称形式）", "The State of New Jersey lies between the Atlantic Ocean and New York City. （来源：词典风格）", "美国州名", "/steɪt əv nuː ˈdʒɜːr.zi/"],
  ["New Mexico", "新墨西哥州（美国西南部，干旱多沙漠，印第安历史丰富）", "New Mexico is a southwestern state with a dry climate and a rich Native American history. （来源：词典风格）", "美国州名", "/nuː ˈmek.sɪ.koʊ/"],
  ["State of New Mexico", "新墨西哥州（New Mexico 的官方全称形式）", "The State of New Mexico is home to the Los Alamos National Laboratory. （来源：词典风格）", "美国州名", "/steɪt əv nuː ˈmek.sɪ.koʊ/"],
  ["New York", "纽约州（美国东北部，纽约市与尼亚加拉瀑布所在地）", "Have you ever heard the one about alligators living in New York sewers? （来源：TPO5-L2 模因理论）", "美国州名", "/nuː ˈjɔːrk/"],
  ["State of New York", "纽约州（New York 的官方全称形式）", "The State of New York contains the largest city in the United States, as well as the Niagara Falls. （来源：词典风格）", "美国州名", "/steɪt əv nuː ˈjɔːrk/"],
  ["North Carolina", "北卡罗来纳州（美国东南部，研究三角区高校云集）", "North Carolina is a southeastern state known for its research universities and coastal beaches. （来源：词典风格）", "美国州名", "/nɔːrθ ˌker.əˈlaɪ.nə/"],
  ["State of North Carolina", "北卡罗来纳州（North Carolina 的官方全称形式）", "The State of North Carolina is a leader in technology research, thanks to the universities of the Research Triangle. （来源：词典风格）", "美国州名", "/steɪt əv nɔːrθ ˌker.əˈlaɪ.nə/"],
  ["North Dakota", "北达科他州（美国北部大平原，石油与小麦资源丰富）", "North Dakota is a northern Great Plains state rich in oil and wheat. （来源：词典风格）", "美国州名", "/nɔːrθ dəˈkoʊ.t̬ə/"],
  ["State of North Dakota", "北达科他州（North Dakota 的官方全称形式）", "The State of North Dakota has one of the largest oil fields in the country. （来源：词典风格）", "美国州名", "/steɪt əv nɔːrθ dəˈkoʊ.t̬ə/"],
  ["Ohio", "俄亥俄州（美国中西部，制造业历史悠久）", "Ohio is a Midwestern state with a long history of manufacturing. （来源：词典风格）", "美国州名", "/oʊˈhaɪ.oʊ/"],
  ["State of Ohio", "俄亥俄州（Ohio 的官方全称形式）", "The State of Ohio is bordered to the south by the Ohio River. （来源：词典风格）", "美国州名", "/steɪt əv oʊˈhaɪ.oʊ/"],
  ["Oklahoma", "俄克拉何马州（美国中部，龙卷风走廊地带，石油资源丰富）", "Oklahoma is located in the central part of the United States, where tornadoes are common. （来源：词典风格）", "美国州名", "/ˌoʊ.kləˈhoʊ.mə/"],
  ["State of Oklahoma", "俄克拉何马州（Oklahoma 的官方全称形式）", "The State of Oklahoma has a large Native American population and rich oil reserves. （来源：词典风格）", "美国州名", "/steɪt əv ˌoʊ.kləˈhoʊ.mə/"],
  ["Oregon", "俄勒冈州（美国西北太平洋沿岸，森林与火山众多）", "Oregon is a Pacific Northwest state known for its forests, mountains, and rainy climate. （来源：词典风格）", "美国州名", "/ˈɔːr.ɪ.ɡən/"],
  ["State of Oregon", "俄勒冈州（Oregon 的官方全称形式）", "The State of Oregon is famous for its scenic coastline along the Pacific Ocean. （来源：词典风格）", "美国州名", "/steɪt əv ˈɔːr.ɪ.ɡən/"],
  ["Pennsylvania", "宾夕法尼亚州（美国东部，费城与匹兹堡所在地，独立战争核心州）", "Uh, Alice Neel painted portraits; um, she was born in Pennsylvania and she lived from 1900 to 1984. （来源：TPO21-L6 爱丽丝尼尔）", "美国州名", "/ˌpen.səlˈveɪ.ni.ə/"],
  ["State of Pennsylvania", "宾夕法尼亚州（Pennsylvania 的官方全称形式）", "The State of Pennsylvania was once a major center of coal and steel production. （来源：词典风格）", "美国州名", "/steɪt əv ˌpen.səlˈveɪ.ni.ə/"],
  ["Rhode Island", "罗得岛州（美国面积最小的州，新英格兰地区）", "Rhode Island is the smallest state in the United States by area. （来源：词典风格）", "美国州名", "/roʊd ˈaɪ.lənd/"],
  ["State of Rhode Island", "罗得岛州（Rhode Island 的官方全称形式）", "The State of Rhode Island has a long tradition of sailing and shipbuilding. （来源：词典风格）", "美国州名", "/steɪt əv roʊd ˈaɪ.lənd/"],
  ["South Carolina", "南卡罗来纳州（美国东南部，查尔斯顿等历史名城）", "South Carolina is a southeastern state with historic coastal cities like Charleston. （来源：词典风格）", "美国州名", "/saʊθ ˌker.əˈlaɪ.nə/"],
  ["State of South Carolina", "南卡罗来纳州（South Carolina 的官方全称形式）", "The State of South Carolina produces much of the country's peaches and tobacco. （来源：词典风格）", "美国州名", "/steɪt əv saʊθ ˌker.əˈlaɪ.nə/"],
  ["South Dakota", "南达科他州（美国北部大平原，拉什莫尔山所在地）", "South Dakota is famous for Mount Rushmore, a monument carved into a mountainside. （来源：词典风格）", "美国州名", "/saʊθ dəˈkoʊ.t̬ə/"],
  ["State of South Dakota", "南达科他州（South Dakota 的官方全称形式）", "The State of South Dakota attracts millions of visitors to the Black Hills every year. （来源：词典风格）", "美国州名", "/steɪt əv saʊθ dəˈkoʊ.t̬ə/"],
  ["Tennessee", "田纳西州（美国东南部，纳什维尔是乡村音乐之都）", "Tennessee is known as the home of country music, centered in Nashville. （来源：词典风格）", "美国州名", "/ˌten.əˈsiː/"],
  ["State of Tennessee", "田纳西州（Tennessee 的官方全称形式）", "The State of Tennessee is named after the Tennessee River that flows through it. （来源：词典风格）", "美国州名", "/steɪt əv ˌten.əˈsiː/"],
  ["Texas", "得克萨斯州（美国面积第二大的州，石油与牛仔文化闻名）", "Texas is the second largest state in the United States and a major producer of oil. （来源：词典风格）", "美国州名", "/ˈtek.səs/"],
  ["State of Texas", "得克萨斯州（Texas 的官方全称形式）", "The State of Texas has a strong cowboy and cattle-ranching tradition. （来源：词典风格）", "美国州名", "/steɪt əv ˈtek.səs/"],
  ["Utah", "犹他州（美国西部，大盐湖与众多国家公园所在地）", "Utah is a western state famous for its national parks and the Great Salt Lake. （来源：词典风格）", "美国州名", "/ˈjuː.tɑː/"],
  ["State of Utah", "犹他州（Utah 的官方全称形式）", "The State of Utah is home to several of the most beautiful national parks in the country. （来源：词典风格）", "美国州名", "/steɪt əv ˈjuː.tɑː/"],
  ["Vermont", "佛蒙特州（美国新英格兰地区，枫糖浆与绿山闻名）", "Vermont is a small New England state known for its maple syrup and green mountains. （来源：词典风格）", "美国州名", "/vərˈmɑːnt/"],
  ["State of Vermont", "佛蒙特州（Vermont 的官方全称形式）", "The State of Vermont produces most of the maple syrup made in the United States. （来源：词典风格）", "美国州名", "/steɪt əv vərˈmɑːnt/"],
  ["Virginia", "弗吉尼亚州（美国东部，早期英国殖民地詹姆斯敦所在地）", "Virginia was one of the first English colonies in North America, founded at Jamestown in 1607. （来源：词典风格）", "美国州名", "/vərˈdʒɪn.jə/"],
  ["State of Virginia", "弗吉尼亚州（Virginia 的官方全称形式）", "The State of Virginia has played an important role throughout American history. （来源：词典风格）", "美国州名", "/steɪt əv vərˈdʒɪn.jə/"],
  ["Washington", "华盛顿州（美国西北太平洋沿岸，西雅图是最大城市）", "Uh, the Kennedy Center in Washington, D.C., you may, maybe you've been there, or Lincoln Center in New York? （来源：TPO4-L6 政府对艺术的支持）", "美国州名", "/ˈwɑː.ʃɪŋ.tən/"],
  ["State of Washington", "华盛顿州（Washington 的官方全称形式，注意区别于首都 Washington, D.C.）", "The State of Washington is named after the first president of the United States. （来源：词典风格）", "美国州名", "/steɪt əv ˈwɑː.ʃɪŋ.tən/"],
  ["West Virginia", "西弗吉尼亚州（美国东部阿巴拉契亚山区，煤矿资源丰富）", "West Virginia is a mountainous state located in the Appalachian region. （来源：词典风格）", "美国州名", "/west vərˈdʒɪn.jə/"],
  ["State of West Virginia", "西弗吉尼亚州（West Virginia 的官方全称形式）", "The State of West Virginia is one of the leading producers of coal in the country. （来源：词典风格）", "美国州名", "/steɪt əv west vərˈdʒɪn.jə/"],
  ["Wisconsin", "威斯康星州（美国中北部，乳制品闻名，绰号“美国的奶制品之乡”）", "Wisconsin is known as America's Dairyland because of its cheese and milk production. （来源：词典风格）", "美国州名", "/wɪsˈkɑːn.sɪn/"],
  ["State of Wisconsin", "威斯康星州（Wisconsin 的官方全称形式）", "The State of Wisconsin borders two of the Great Lakes: Lake Michigan and Lake Superior. （来源：词典风格）", "美国州名", "/steɪt əv wɪsˈkɑːn.sɪn/"],
  ["Wyoming", "怀俄明州（美国人口最少的州，黄石国家公园大部分位于境内）", "Wyoming is the least populated state in the United States and contains most of Yellowstone National Park. （来源：词典风格）", "美国州名", "/waɪˈoʊ.mɪŋ/"],
  ["State of Wyoming", "怀俄明州（Wyoming 的官方全称形式）", "The State of Wyoming is famous for its national parks and wide-open plains. （来源：词典风格）", "美国州名", "/steɪt əv waɪˈoʊ.mɪŋ/"],
  ["the Renaissance", "文艺复兴（14-17世纪，复兴古希腊罗马古典文化，强调人文主义；托福常把它作为后续一切运动的“起点”）", "And they took classical theater and reproduced it in the Renaissance time. （来源：TPO45-L2 文艺复兴时期的艺术技艺）", "历史运动", "/ðə ˌren.əˈsɑːns/"],
  ["Humanism", "人文主义（文艺复兴的核心思想，重新发现人的价值与潜力）", "Humanism, the belief that human beings and their achievements are worthy of study and celebration, was the central idea of the Renaissance. （来源：词典风格）", "历史运动", "/ˈhjuː.mə.nɪ.zəm/"],
  ["the Reformation", "宗教改革（16世纪，反对罗马天主教会的权威，建立新教；常考其对印刷术普及与欧洲政治格局的影响）", "The Reformation challenged the authority of the Roman Catholic Church in sixteenth-century Europe and gave rise to the Protestant churches. （来源：词典风格）", "历史运动", "/ðə ˌref.ərˈmeɪ.ʃən/"],
  ["Protestantism", "新教，新教主义（宗教改革的产物，因“抗议”protest 天主教会而得名）", "Protestantism grew out of the Reformation, taking its name from the protest against the authority of the Catholic Church. （来源：词典风格）", "历史运动", "/ˈprɑː.tɪ.stən.tɪ.zəm/"],
  ["Martin Luther", "马丁·路德（16世纪宗教改革领袖，他的抗议推动了新教的建立）", "Martin Luther, a German monk, sparked the Reformation when he protested against the sale of indulgences by the Catholic Church. （来源：词典风格）", "历史运动", "/ˈmɑːr.tɪn ˈluː.θər/"],
  ["the Scientific Revolution", "科学革命（16-17世纪，用观察与实验代替迷信，确立科学方法；直接催生了启蒙运动）", "The Scientific Revolution of the sixteenth and seventeenth centuries replaced superstition with careful observation and experiment. （来源：词典风格）", "历史运动", "/ðə ˌsaɪ.ənˈtɪf.ɪk ˌrev.əˈluː.ʃən/"],
  ["Scientific Method", "科学方法（基于观察 observation 与实验 experiment 的研究方法，科学革命期间确立）", "In the late 1800s, people were interested in the scientific method, as well as rational philosophy—which says that people can discover the truth by using reason and factual analysis. （来源：TPO50-L5）", "历史运动", "/ˌsaɪ.ənˈtɪf.ɪk ˈmeθ.əd/"],
  ["Copernicus", "哥白尼（提出日心说：地球和其他行星绕太阳运行）", "Copernicus proposed that the Earth and the other planets revolve around the Sun, overturning the ancient belief that the Earth was the center of the universe. （来源：词典风格）", "历史运动", "/koʊˈpɜːr.nɪ.kəs/"],
  ["Galileo", "伽利略（用望远镜观测天体，支持日心说）", "In the early 1600s, based on his observations of sunspots, Galileo proposed a new hypothesis. （来源：TPO18-L2 太阳黑子）", "历史运动", "/ˌɡæl.ɪˈleɪ.oʊ/"],
  ["Newton", "牛顿（经典力学奠基人，万有引力与运动定律的提出者）", "Newton's laws of motion and universal gravitation became the foundation of classical physics. （来源：词典风格）", "历史运动", "/ˈnuː.tən/"],
  ["Realism", "现实主义（19世纪中后期，反对浪漫主义的幻想，如实描绘普通人与底层劳动人民的日常生活；常考与浪漫主义对比，文学对应福楼拜/狄更斯，绘画对应库尔贝 Courbet）", "Realism was important in the sense that she wanted to show people as they really were—much like a photographer would. （来源：TPO21-L6 爱丽丝尼尔）", "历史运动", "/ˈriː.ə.lɪ.zəm/"],
  ["Impressionism", "印象派（19世纪末，反对学院派精细画法，捕捉瞬间的光影和色彩；托福艺术类讲座第一高频，常考其如何受摄影术 photography 的影响）", "Impressionist painters tried to capture the momentary effects of light and color with loose brushstrokes and bright pigments. （来源：词典风格）", "历史运动", "/ɪmˈpreʃ.ə.nɪ.zəm/"],
  ["Modernism", "现代主义（20世纪初，打破一切传统规则，追求创新、抽象、碎片化；源于一战后的社会幻灭感 disillusionment）", "Modernism, which emerged after World War I, broke with traditional rules and embraced experimentation and abstraction. （来源：词典风格）", "历史运动", "/ˈmɑː.dər.nɪ.zəm/"],
  ["methane", "甲烷（最简单的碳氢化合物，天然气的主要成分，强效温室气体）", "Another gas associated with the spread of agriculture is methane, which forms in large concentrations above wetlands. （来源：TPO20-L3）", "能源环境", "/ˈmeθ.eɪn/"],
  ["natural gas", "天然气（以甲烷为主的化石燃料，燃烧比煤更清洁）", "Like coal and natural gas, petroleum has been formed over millions of years from the remains of prehistoric plants and animals. （来源：TPO50-L6）", "能源环境", "/ˈnætʃ.ər.əl ɡæs/"],
  ["greenhouse gas", "温室气体（吸收并重新辐射红外辐射、导致温室效应的气体，如二氧化碳、甲烷）", "The concentration of carbon dioxide and methane gas—greenhouse gases—in the atmosphere reaches its peak just after the beginning of the interglacial period. （来源：TPO20-L3）", "能源环境", "/ˈɡriːn.haʊs ɡæs/"],
  ["greenhouse effect", "温室效应（大气中的温室气体留住热量、使地球表面变暖的过程）", "So what gas do you think was the first suspect in causing the greenhouse effect? （来源：TPO22-L3）", "能源环境", "/ˈɡriːn.haʊs ɪˈfekt/"],
  ["global warming", "全球变暖（近几十年来地球平均气温的持续上升）", "There's compelling evidence that global warming will be a significant driver of many plant and animal extinctions in this century. （来源：TPO25-L2）", "能源环境", "/ˈɡloʊ.bəl ˈwɔːr.mɪŋ/"],
  ["climate change", "气候变化（长期的天气模式变化，常指人为导致的全球变暖及其影响）", "Currently, there's no public policy on using assisted migration to help species survive climate change. （来源：TPO25-L2）", "能源环境", "/ˈklaɪ.mət tʃeɪndʒ/"],
  ["carbon dioxide", "二氧化碳（主要温室气体之一，化石燃料燃烧的主要产物）", "Studies indicate that four billion years ago, carbon dioxide levels in the atmosphere were much higher than today's levels. （来源：TPO22-L3）", "能源环境", "/ˈkɑːr.bən daɪˈɑːk.saɪd/"],
  ["carbon monoxide", "一氧化碳（不完全燃烧产生的有毒气体）", "Carbon monoxide is a colorless, odorless gas produced by the incomplete combustion of fuel, and exposure to high levels of it can be fatal. （来源：词典风格）", "能源环境", "/ˈkɑːr.bən məˈnɑːk.saɪd/"],
  ["fossil fuel", "化石燃料（煤、石油、天然气等由古生物残骸形成的燃料）", "The burning of fossil fuels tends to put a lot of CO2 into the atmosphere. （来源：TPO20-L3）", "能源环境", "/ˈfɑː.səl ˈfjuː.əl/"],
  ["hydrocarbon", "碳氢化合物（只含碳和氢的化合物，石油和天然气的主要成分）", "A hydrocarbon is a compound made up of hydrogen and carbon atoms, and petroleum consists of a complex mixture of these compounds. （来源：词典风格）", "能源环境", "/ˌhaɪ.drəˈkɑːr.bən/"],
  ["permafrost", "永久冻土（常年冻结的土层，融化时会释放甲烷和二氧化碳）", "Beneath the active layer is a second layer called permafrost, which is frozen all year round and is impermeable to water. （来源：TPO09-L3）", "能源环境", "/ˈpɜːr.mə.frɔːst/"],
  ["wetland", "湿地（沼泽、泥炭地等，是甲烷的重要自然来源）", "Methane forms in large concentrations above wetlands, and the cultivation of certain grains creates vast areas of artificial wetlands. （来源：TPO20-L3）", "能源环境", "/ˈwet.lənd/"],
  ["livestock", "牲畜（牛等反刍动物的消化过程会排放甲烷）", "Early farmers started clearing forests, and livestock produced a lot of extra methane. （来源：TPO15-L5）", "能源环境", "/ˈlaɪv.stɑːk/"],
  ["anaerobic", "厌氧的（在无氧条件下进行的；甲烷常由厌氧微生物产生）", "Anaerobic bacteria break down organic matter in environments where oxygen is absent, releasing methane as a by-product of the process. （来源：词典风格）", "能源环境", "/ˌæn.əˈroʊ.bɪk/"],
  ["microorganism", "微生物（细菌等微小生物，参与有机物分解与甲烷产生）", "What they discovered was that microorganisms—bacteria—had taken over both functions of the biological community: the recycling of waste materials and the production of energy. （来源：TPO15-L3）", "能源环境", "/ˌmaɪ.kroʊˈɔːr.ɡə.nɪz.əm/"],
  ["carbon cycle", "碳循环（碳在生物圈、大气、海洋和岩石之间循环的过程）", "The carbon cycle describes the movement of carbon between the atmosphere, the oceans, and living organisms. （来源：词典风格）", "能源环境", "/ˈkɑːr.bən ˈsaɪ.kəl/"],
  ["carbon footprint", "碳足迹（个人或组织活动直接和间接产生的温室气体总量）", "Flying less and eating less meat are two of the simplest ways to reduce your carbon footprint. （来源：词典风格）", "能源环境", "/ˈkɑːr.bən ˈfʊt.prɪnt/"],
  ["carbon sequestration", "碳封存（捕获并长期储存二氧化碳以减缓气候变化的技术）", "Carbon sequestration, the capture and long-term storage of carbon dioxide, is one of the technologies being investigated as a way of slowing the rise in atmospheric CO2 levels. （来源：词典风格）", "能源环境", "/ˈkɑːr.bən ˌsiː.kwəˈstreɪ.ʃən/"],
  ["feedback loop", "反馈回路（一个变化触发另一个变化，进而又加强或减弱最初变化的过程）", "Melting permafrost creates a feedback loop: as the ground thaws, it releases methane, which traps more heat and causes still more thawing. （来源：词典风格）", "能源环境", "/ˈfiːd.bæk luːp/"],
  ["methane hydrate", "甲烷水合物（低温高压下甲烷与水形成的冰状固体，储藏在海底与冻土中）", "Methane hydrate is an ice-like solid in which methane molecules are trapped within a lattice of water molecules, and huge deposits of it lie beneath the seafloor. （来源：词典风格）", "能源环境", "/ˈmeθ.eɪn ˈhaɪ.dreɪt/"],
  ["biogas", "沼气（有机物厌氧发酵产生的可燃气体，主要成分是甲烷）", "Biogas, which consists mainly of methane, is produced when organic waste is broken down by bacteria in the absence of oxygen. （来源：词典风格）", "能源环境", "/ˈbaɪ.oʊ.ɡæs/"],
  ["combustion", "燃烧（物质与氧气剧烈反应放出光和热的化学过程）", "The combustion of fossil fuels such as coal and oil releases carbon dioxide and other pollutants into the atmosphere. （来源：词典风格）", "能源环境", "/kəmˈbʌs.tʃən/"],
  ["emission", "排放物（排入大气的气体或污染物）", "On Earth the main source of naturally occurring VLF emissions is lightning, which generates a pulse of radio waves every time it flashes. （来源：TPO43-L6）", "能源环境", "/ɪˈmɪʃ.ən/"],
  ["atmosphere", "大气层（包围地球的气体层）", "Most of the meteors are very small, and they burn up soon after entering the Earth's atmosphere. （来源：TPO13-L6）", "能源环境", "/ˈæt.məs.fɪr/"],
  ["ozone", "臭氧（大气中的一种气体；平流层臭氧保护地球免受紫外线伤害）", "The ozone layer in the stratosphere shields the Earth from most of the Sun's harmful ultraviolet radiation. （来源：词典风格）", "能源环境", "/ˈoʊ.zoʊn/"],
  ["ultraviolet radiation", "紫外线辐射（太阳发出的短波辐射）", "The ozone layer absorbs most of the Sun's ultraviolet radiation before it reaches the Earth's surface. （来源：词典风格）", "能源环境", "/ˌʌl.trəˈvaɪə.lət ˌreɪ.diˈeɪ.ʃən/"],
  ["hydraulic fracturing", "水力压裂（向岩层高压注水以开采页岩气或石油的技术，常简写 fracking）", "Hydraulic fracturing, commonly known as fracking, involves injecting fluid at high pressure into rock formations to extract oil and natural gas. （来源：词典风格）", "能源环境", "/haɪˈdrɔː.lɪk ˈfræk.tʃər.ɪŋ/"],
  ["shale gas", "页岩气（储存在页岩中的天然气）", "Advances in drilling technology have made it possible to extract large quantities of shale gas from rock formations that were once considered uneconomical. （来源：词典风格）", "能源环境", "/ʃeɪl ɡæs/"],
  ["renewable energy", "可再生能源（太阳能、风能、水能等可再生的能源）", "There's growing interest these days in generating electricity from renewable energy sources, from developing wind farms to tapping into an underground source of geothermal energy. （来源：TPO44-L6）", "能源环境", "/rɪˈnuː.ə.bəl ˈen.ər.dʒi/"],
  ["solar panel", "太阳能电池板（把阳光转化为电能的装置）", "More and more homeowners are installing solar panels on their roofs to generate their own electricity. （来源：词典风格）", "能源环境", "/ˈsoʊ.lər ˈpæn.əl/"],
  ["wind turbine", "风力涡轮机（利用风力发电的装置）", "Wind turbines convert the kinetic energy of the wind into electricity without burning any fuel. （来源：词典风格）", "能源环境", "/wɪnd ˈtɜːr.baɪn/"],
  ["geothermal energy", "地热能（来自地球内部的热能）", "There's growing interest these days in generating electricity from renewable energy sources, from developing wind farms to tapping into an underground source of geothermal energy. （来源：TPO44-L6）", "能源环境", "/ˌdʒiː.oʊˈθɜːr.məl ˈen.ər.dʒi/"],
  ["nuclear power", "核能发电（利用核裂变释放的能量发电）", "Nuclear power generates large amounts of electricity without emitting carbon dioxide, but it produces radioactive waste that must be stored safely for thousands of years. （来源：词典风格）", "能源环境", "/ˈnuː.kli.ər ˈpaʊ.ər/"],
  ["sediment", "沉积物（由风、水或冰搬运并沉淀的碎屑物质）", "Sediment, as you know, is material like sand, gravel, and fossil fragments that is transported by natural processes like wind, water flow, or the movement of glaciers. （来源：TPO15-L5）", "能源环境", "/ˈsed.ə.mənt/"],
  ["peat", "泥炭（部分分解的植物残体堆积物，可缓慢形成煤）", "Peat is formed from partially decomposed plant material in waterlogged conditions, and when drained or burned it releases the carbon it has stored over centuries. （来源：词典风格）", "能源环境", "/piːt/"],
  ["decompose", "分解（有机物在微生物作用下腐烂降解）", "When plants die, they decompose, and the phosphorus is recycled back into the soil. （来源：TPO10-L5）", "能源环境", "/ˌdiː.kəmˈpoʊz/"],
  ["smog", "烟雾（由污染物和阳光反应形成的有害空气混合物）", "Smog is a mixture of pollutants and fog that forms over cities when vehicle exhaust and industrial emissions react with sunlight. （来源：词典风格）", "能源环境", "/smɑːɡ/"],
  ["acid rain", "酸雨（二氧化硫和氮氧化物与水汽反应形成的酸性降水）", "Acid rain, caused by sulfur dioxide and nitrogen oxides reacting with moisture in the atmosphere, can damage forests and erode stone buildings. （来源：词典风格）", "能源环境", "/ˈæs.ɪd reɪn/"],
  ["sustainable", "可持续的（能长期维持而不耗尽资源的）", "A sustainable approach to development meets the needs of the present without compromising the ability of future generations to meet their own needs. （来源：词典风格）", "能源环境", "/səˈsteɪ.nə.bəl/"],
  ["recycle", "回收利用（把废弃物加工成可再利用的材料）", "Water changes back and forth from lakes and oceans to vapor, and then back to water again when it falls as rain or snow—it's constantly being recycled. （来源：TPO24-L4）", "能源环境", "/ˌriːˈsaɪ.kəl/"],
  ["transverse flute", "横吹长笛（横持吹奏的长笛，区别于直吹的竖笛）", "The technical advances we've seen in the development of some of the instruments—you remember, the transverse flute, the clarinet, and so on. （来源：TPO16-L3）", "乐器", "/trænzˈvɜːrs fluːt/"],
  ["flute", "长笛（木管乐器；英语中一般即指横吹长笛）", "You remember the transverse flute, the clarinet, and so on. （来源：TPO16-L3）", "乐器", "/fluːt/"],
  ["piccolo", "短笛（长笛的缩小版，音域最高）", "The piccolo, the smallest member of the flute family, produces the highest notes in the orchestra. （来源：词典风格）", "乐器", "/ˈpɪk.ə.loʊ/"],
  ["recorder", "竖笛（直吹的木管乐器，中小学音乐课常见）", "The recorder, a simple end-blown flute, is often the first instrument taught in elementary school. （来源：词典风格）", "乐器", "/rɪˈkɔːr.dər/"],
  ["clarinet", "单簧管（黑管，单簧片的木管乐器）", "The technical advances we've seen in the development of some of the instruments, like the transverse flute and the clarinet, and so on. （来源：TPO16-L3）", "乐器", "/ˌkler.əˈnet/"],
  ["oboe", "双簧管（双簧片的木管乐器，音色略带鼻音）", "The oboe, a double-reed woodwind, plays the tuning note A that the rest of the orchestra tunes to. （来源：词典风格）", "乐器", "/ˈoʊ.boʊ/"],
  ["bassoon", "巴松管（大管，木管乐器中音域最低）", "The bassoon, the lowest of the woodwind instruments, provides a rich, reedy bass line. （来源：词典风格）", "乐器", "/bəˈsuːn/"],
  ["saxophone", "萨克斯管（虽用金属制成，但属于木管乐器家族）", "I'd love to have a place to practice my saxophone without worrying about disturbing people. （来源：TPO46-L1）", "乐器", "/ˈsæk.sə.foʊn/"],
  ["English horn", "英国管（双簧管的变体，音色更低沉柔和）", "The English horn, larger than the oboe, has a lower and more melancholy tone. （来源：词典风格）", "乐器", "/ˈɪŋ.ɡlɪʃ hɔːrn/"],
  ["trumpet", "小号（音色明亮的铜管乐器）", "How many of you play a brass instrument, like a trumpet or trombone? （来源：TPO46-L6）", "乐器", "/ˈtrʌm.pɪt/"],
  ["cornet", "短号（与小号相似但音色更柔和）", "The cornet resembles the trumpet in shape but produces a softer, rounder tone. （来源：词典风格）", "乐器", "/kɔːrˈnet/"],
  ["French horn", "圆号（法国号，铜管乐器中音色最圆润）", "The French horn's long coiled tube and flared bell give it the warmest tone in the brass family. （来源：词典风格）", "乐器", "/frentʃ hɔːrn/"],
  ["trombone", "长号（通过伸缩滑管改变音高的铜管乐器）", "If your trombone was made of pure copper or pure zinc, it wouldn't sound nearly as beautiful as a brass trombone. （来源：TPO46-L6）", "乐器", "/trɑːmˈboʊn/"],
  ["tuba", "大号（铜管乐器中体积最大、音域最低）", "The tuba, the largest and lowest-pitched brass instrument, anchors the orchestra's bass line. （来源：词典风格）", "乐器", "/ˈtuː.bə/"],
  ["violin", "小提琴（弦乐四重奏与管弦乐团的核心乐器）", "Creativity comes through learning to play the violin, using the object for the purpose it was intended. （来源：TPO49-L3）", "乐器", "/ˌvaɪəˈlɪn/"],
  ["viola", "中提琴（比小提琴稍大，音色更厚重）", "The viola is slightly larger than the violin and sounds a fifth lower. （来源：词典风格）", "乐器", "/viˈoʊ.lə/"],
  ["cello", "大提琴（演奏时夹在两膝之间）", "Everyone's into sports and I'm more artsy—into music. I play the cello. （来源：TPO5-L1）", "乐器", "/ˈtʃel.oʊ/"],
  ["double bass", "低音提琴（弦乐器中体积最大、音域最低）", "I have taken some music courses and I do play the double bass. （来源：TPO47-L1）", "乐器", "/ˌdʌb.əl ˈbeɪs/"],
  ["harp", "竖琴（拨弦乐器，管弦乐团中体型最大）", "The harp's plucked strings produce a shimmering sound that is unique in the orchestra. （来源：词典风格）", "乐器", "/hɑːrp/"],
  ["guitar", "吉他（六弦拨弦乐器，流行音乐核心）", "Pressing a key of a harpsichord causes a tiny quill to pluck the strings inside the instrument, much the same as a guitar pick plucks the strings of a guitar. （来源：TPO16-L3）", "乐器", "/ɡɪˈtɑːr/"],
  ["lute", "鲁特琴（文艺复兴时期流行的拨弦乐器，托福艺术史高频）", "The lute, with its pear-shaped body and many strings, was the most popular instrument of the Renaissance. （来源：词典风格）", "乐器", "/luːt/"],
  ["banjo", "班卓琴（美国民谣与乡村音乐常用的拨弦乐器）", "Banjos are of African American origin, and settlers in Appalachia adopted banjos for their folk music. （来源：TPO47-L1）", "乐器", "/ˈbæn.dʒoʊ/"],
  ["mandolin", "曼陀林（梨形琴身的拨弦乐器）", "The mandolin's paired strings are plucked rapidly to produce a bright, tremulous sound. （来源：词典风格）", "乐器", "/ˌmæn.dəˈlɪn/"],
  ["drum", "鼓（打击乐器，用鼓槌或手敲击鼓面发声）", "Pressing the keys of a piano causes tiny felt-covered hammers to strike the strings inside the instrument, like drumsticks striking the head of a drum. （来源：TPO16-L3）", "乐器", "/drʌm/"],
  ["snare drum", "小军鼓（鼓面下装有响弦，声音清脆）", "The snare drum's crisp sound comes from wires stretched across its lower head. （来源：词典风格）", "乐器", "/sner drʌm/"],
  ["bass drum", "大鼓（打击乐器中体积最大、声音最低沉）", "The bass drum produces a deep, resonant boom that can be felt as much as heard. （来源：词典风格）", "乐器", "/beɪs drʌm/"],
  ["timpani", "定音鼓（管弦乐团中的大鼓，可调音高）", "Timpani are kettle-shaped drums that can be tuned to specific pitches. （来源：词典风格）", "乐器", "/ˈtɪm.pə.ni/"],
  ["cymbal", "钹（两片金属圆盘相击发声）", "The crash of the cymbal adds brilliance to the loudest passages of a symphony. （来源：词典风格）", "乐器", "/ˈsɪm.bəl/"],
  ["triangle", "三角铁（金属棒敲击三角形钢条发声）", "The triangle, a small steel bar struck with a metal beater, produces a bright, ringing tone. （来源：词典风格）", "乐器", "/ˈtraɪ.æŋ.ɡəl/"],
  ["tambourine", "铃鼓（鼓面四周装有金属小铃的打击乐器）", "The tambourine pairs a small drum head with metal jingles around its rim. （来源：词典风格）", "乐器", "/ˌtæm.bəˈriːn/"],
  ["xylophone", "木琴（由一排木条组成的打击乐器）", "The xylophone's wooden bars are struck with mallets to produce short, sharp tones. （来源：词典风格）", "乐器", "/ˈzaɪ.lə.foʊn/"],
  ["marimba", "马林巴（类似木琴但音色更低沉柔和）", "The marimba, with its wooden bars and resonating tubes, produces a deep, mellow tone. （来源：词典风格）", "乐器", "/məˈrɪm.bə/"],
  ["glockenspiel", "钟琴（由金属音条组成的打击乐器，音色清脆如铃）", "The glockenspiel's metal bars produce a bright, bell-like tone. （来源：词典风格）", "乐器", "/ˈɡlɑː.kən.spiːl/"],
  ["piano", "钢琴（键盘乐器，击弦发声，全名 pianoforte）", "The word 'piano' is short for 'pianoforte', a combination of the Italian words for 'soft' and 'loud'. （来源：TPO16-L3）", "乐器", "/piˈæn.oʊ/"],
  ["organ", "管风琴（靠气流吹响音管的键盘乐器，常见于教堂）", "Organs could mimic a number of instruments and also do some sound effects, so they were starting to replace live orchestras in some movie theaters. （来源：TPO22-L6）", "乐器", "/ˈɔːr.ɡən/"],
  ["harpsichord", "羽管键琴（大键琴，巴洛克时期的主要键盘乐器，拨弦发声）", "Unlike the harpsichord, which came before it, the piano is a percussion instrument. （来源：TPO16-L3）", "乐器", "/ˈhɑːrp.sɪ.kɔːrd/"],
  ["accordion", "手风琴（拉动风箱使簧片振动的键盘乐器）", "The accordion produces sound when the player expands and compresses its bellows. （来源：词典风格）", "乐器", "/əˈkɔːr.di.ən/"],
  ["synthesizer", "电子合成器（用电子电路产生和修改声音的乐器）", "The synthesizer can generate sounds electronically that no acoustic instrument can produce. （来源：词典风格）", "乐器", "/ˈsɪn.θə.saɪ.zər/"],
  ["bagpipe", "风笛（苏格兰传统乐器，靠风袋供气）", "The bagpipe's continuous drone comes from air held in a bag under the player's arm. （来源：词典风格）", "乐器", "/ˈbæɡ.paɪp/"],
  ["sitar", "西塔琴（印度传统拨弦乐器，琴颈很长）", "The sitar, a long-necked Indian instrument, produces a distinctive buzzing tone from its sympathetic strings. （来源：词典风格）", "乐器", "/sɪˈtɑːr/"],
  ["pan flute", "排箫（一排长短不同的管子绑在一起吹奏）", "The pan flute consists of tubes of different lengths bound together in a row. （来源：词典风格）", "乐器", "/pæn fluːt/"],
  ["harmonica", "口琴（靠吹吸簧片发声的小型乐器）", "The harmonica is played by blowing and drawing air through its metal reeds. （来源：词典风格）", "乐器", "/hɑːrˈmɑː.nɪ.kə/"],
  ["didgeridoo", "迪吉里杜管（澳洲原住民的木管乐器，发出低沉持续的音）", "The didgeridoo, made from a hollowed tree trunk, produces a deep, continuous drone. （来源：词典风格）", "乐器", "/ˌdɪdʒ.ər.iˈduː/"],
  ["felt", "毛毡（名词）；也是 feel 的过去式", "Pressing the keys of a piano causes tiny felt-covered hammers to strike the strings inside the instrument. （来源：TPO16-L3）", "多义词", "/felt/"],
  ["hands", "手（复数）；钟表的指针（the hands of a clock）", "For me it's her face and hands—I think they're really expressive. （来源：TPO19-L6）", "多义词", "/hændz/"],
  ["pupil", "学生；瞳孔（眼睛的黑色部分）", "The doctor shone a light into the pupil of the patient's eye. （来源：词典风格）", "多义词", "/ˈpjuː.pəl/"],
  ["iris", "虹膜（眼睛有颜色的部分）；鸢尾花", "The iris of her eye was a pale blue, like the irises blooming in the garden. （来源：词典风格）", "多义词", "/ˈaɪ.rɪs/"],
  ["palm", "手掌；棕榈树", "The traveler rested his palm against the rough trunk of a palm tree. （来源：词典风格）", "多义词", "/pɑːm/"],
  ["trunk", "树干；象鼻；汽车后备箱", "The elephant coiled its trunk around the tree trunk. （来源：词典风格）", "多义词", "/trʌŋk/"],
  ["head", "头；首领；源头（河流的源头）", "Why don't we know the exact date when this head was made? （来源：TPO17-L2）", "多义词", "/hed/"],
  ["foot", "脚；英尺（长度单位）；底部", "It is essentially an outdoor shopping area designed just for people on foot. （来源：TPO13-L2）", "多义词", "/fʊt/"],
  ["arm", "手臂；武器（arms）；（机构）分支", "Classical ballet is based on formalized movements: specific positioning of the arms, of the feet, and the body. （来源：TPO24-L3）", "多义词", "/ɑːrm/"],
  ["bat", "蝙蝠；球棒", "The bat emits ultrasonic pulses—very high-pitched sound waves that we can't hear. （来源：TPO7-L3）", "多义词", "/bæt/"],
  ["crane", "鹤；起重机", "A tower crane hoisted the steel beams above the construction site. （来源：词典风格）", "多义词", "/kreɪn/"],
  ["seal", "海豹；密封；印章", "It was a seal of approval—a great encouragement for an artist's career. （来源：TPO8-L3）", "多义词", "/siːl/"],
  ["bear", "熊；忍受；携带", "It's actually a member of the banana family—it even bears little banana-shaped fruits. （来源：TPO2-L3）", "多义词", "/ber/"],
  ["swallow", "燕子；吞咽", "The swallow swooped low over the pond to swallow a flying insect. （来源：词典风格）", "多义词", "/ˈswɑː.loʊ/"],
  ["mole", "鼹鼠；间谍；痣", "The security chief suspected that a mole inside the agency was leaking classified information. （来源：词典风格）", "多义词", "/moʊl/"],
  ["current", "水流；电流；当前的", "The tidal currents are constantly churning up the sediments that rivers deposit in the estuary. （来源：TPO44-L6）", "多义词", "/ˈkɝː.ənt/"],
  ["conductor", "导体（导热导电的材料）；乐队指挥；售票员", "A waveguide usually refers to a device, like a metal conductor, that's used to guide and direct waves. （来源：TPO43-L6）", "多义词", "/kənˈdʌk.tər/"],
  ["pitch", "投掷；音高；沥青", "The violinist adjusted the pitch of each string until it matched the tuning note. （来源：词典风格）", "多义词", "/pɪtʃ/"],
  ["work", "工作；功（物理学中力做的功）", "In physics, work is done when a force moves an object over a distance. （来源：词典风格）", "多义词", "/wɜːrk/"],
  ["mass", "大量；质量（物理学）；群众", "We know the Sun's current rate of mass loss. （来源：TPO22-L3）", "多义词", "/mæs/"],
  ["solution", "解决方案；溶液（化学）", "A solution of antifreeze, like you put in your car in the winter? （来源：TPO18-L6）", "多义词", "/səˈluː.ʃən/"],
  ["cell", "细胞；电池；牢房", "When we try to grow most human cells in a laboratory, they seem programmed to divide only a certain number of times. （来源：TPO12-L2）", "多义词", "/sel/"],
  ["plate", "盘子；（地球）板块；金属板", "The Earth's surface, the crust, is made up of tectonic plates, huge slabs of rocky crust slowly sliding over, under, or past each other. （来源：TPO48-L3）", "多义词", "/pleɪt/"],
  ["fault", "错误；断层（地质）", "We didn't even talk about who should fix this—who was at fault. （来源：TPO21-L3）", "多义词", "/fɔːlt/"],
  ["crust", "面包皮；地壳（地质）", "We especially want to know if any of the mantle, the layer beneath the crust, was exposed by the impact. （来源：TPO5-L3）", "多义词", "/krʌst/"],
  ["mantle", "斗篷；地幔（地质，地壳与地核之间的层）", "Much more than the crust, the mantle contains information about a planet's or Moon's total composition. （来源：TPO5-L3）", "多义词", "/ˈmæn.təl/"],
  ["core", "果核；地核（地球中心）；核心", "The core problem with this 'sixth mass extinction' is human interference. （来源：TPO22-L5）", "多义词", "/kɔːr/"],
  ["fold", "折叠；褶皱（地质，岩层弯曲）", "The Native Americans would cut the bark and fold it into any shape they needed. （来源：TPO7-L5）", "多义词", "/foʊld/"],
  ["note", "笔记；音符；钞票", "Each empty bottle plays one particular musical note. （来源：TPO14-L6）", "多义词", "/noʊt/"],
  ["rest", "休息；休止符（音乐）", "The composer wrote a quarter rest, giving the orchestra a brief moment of silence. （来源：词典风格）", "多义词", "/rest/"],
  ["staff", "员工；五线谱（音乐）；棍杖", "The composer wrote the melody on the five lines of the musical staff. （来源：词典风格）", "多义词", "/stæf/"],
  ["bridge", "桥；琴桥（弦乐器上支撑琴弦的部分）", "Neel employed certain techniques to bridge that contradiction. （来源：TPO21-L6）", "多义词", "/brɪdʒ/"],
  ["bow", "鞠躬；琴弓；弓（射箭）", "The violinist drew the bow across the strings and then bowed to the audience. （来源：词典风格）", "多义词", "/boʊ/"],
  ["scale", "刻度；鳞片；音阶；规模", "Does that mean that solar energy can only be used on a small scale, like heating a home? （来源：TPO12-L6）", "多义词", "/skeɪl/"],
  ["key", "钥匙；琴键；调（音乐）；关键", "Pressing the keys of a piano causes tiny felt-covered hammers to strike the strings inside the instrument. （来源：TPO16-L3）", "多义词", "/kiː/"],
  ["novel", "小说；新颖的（形容词）", "His novels have very unique structures. （来源：TPO23-L4）", "多义词", "/ˈnɑː.vəl/"],
  ["plot", "情节（故事）；地块（土地）；阴谋", "You're reviewing the basics, like plot, setting, and character. （来源：TPO23-L4）", "多义词", "/plɑːt/"],
  ["table", "桌子；表格；把…提交讨论", "Early versions of the periodic table had gaps, missing elements. （来源：TPO8-L6）", "多义词", "/ˈteɪ.bəl/"],
  ["figure", "人物；数字；图形；身材", "Neel painted realistic faces and eyes but bright, distorted figures. （来源：TPO21-L6）", "多义词", "/ˈfɪɡ.jər/"],
  ["mean", "意思是；平均的；刻薄的", "We'd better define exactly what we mean when we talk about states. （来源：TPO22-L2）", "多义词", "/miːn/"],
  ["function", "功能；函数（数学）", "What do you mean, the Roman function? Weren't they just for decoration? （来源：TPO18-L3）", "多义词", "/ˈfʌŋk.ʃən/"],
  ["interest", "兴趣；利息（金融）", "I really do think there would be genuine interest beyond my group. （来源：TPO23-L1）", "多义词", "/ˈɪn.trəst/"],
  ["capital", "首都；资本；大写字母", "The capital city of the Philippines is Manila. （来源：TPO2-L3）", "多义词", "/ˈkæp.ɪ.təl/"],
  ["stock", "库存；股票；高汤", "It has stock characters like a prince and a poor but beautiful peasant girl. （来源：TPO20-L5）", "多义词", "/stɑːk/"],
  ["compound", "化合物；复合的；加剧", "You got specific colors by adding metallic compounds to the other glassmaking ingredients. （来源：TPO16-L6）", "多义词", "/ˈkɑːm.paʊnd/"],
  ["revolution", "革命；旋转（一圈）", "One idea I had was looking at an important world event, like the French Revolution of 1789. （来源：TPO46-L4）", "多义词", "/ˌrev.əˈluː.ʃən/"],
  ["deposit", "存款；沉积物（注意：本词双义；地质化学分类里有话题版例句）", "Over millions of years, groundwater left deposits of a mineral called calcite on the rock within Devils Hole. （来源：TPO17-L3）", "多义词", "/dɪˈpɑː.zɪt/"],
  ["trace", "痕迹；追踪；微量", "Many languages spoken all over the world today can trace their ancestry back to one language, Proto-Indo-European. （来源：TPO19-L2）", "多义词", "/treɪs/"],
  ["press", "按，压；出版社；新闻界", "Before the invention of printing and the printing press, all books and manuscripts were handmade. （来源：TPO15-L2）", "多义词", "/pres/"],
  ["revise", "修订（修改文章）；复习（英式英语）", "You'll have to go back and revise the rest to see how it all fits together. （来源：TPO12-L1）", "多义词", "/rɪˈvaɪz/"],
  ["address", "地址；演讲；处理（问题）", "You haven't changed your mailing address at the administration office. （来源：TPO3-L1）", "多义词", "/əˈdres/"],
  ["season", "季节；给…调味", "Their first calendar was divided into three seasons, each based on the river's changes: inundation, subsidence, and harvest. （来源：TPO17-L5）", "多义词", "/ˈsiː.zən/"],
  ["limestone", "石灰岩（以碳酸钙为主的沉积岩，易被酸腐蚀）", "It's one of the longest and deepest limestone caves not just in the country, but in the world. （来源：TPO16-L2）", "地质化学", "/ˈlaɪm.stoʊn/"],
  ["sulfuric acid", "硫酸（强酸，能腐蚀石灰岩，是某些洞穴的成因）", "Sulfuric acid eats away at limestone—very aggressively—so you get bigger cracks, and then passageways being formed along the openings in the rock. （来源：TPO16-L2）", "地质化学", "/sʌlˈfjʊr.ɪk ˈæs.ɪd/"],
  ["dissolve", "溶解（固体在液体中分散消失；酸把岩石“吃掉”的过程）", "And there's other evidence that flowing water wasn't involved in Lechuguilla; we've said that sulfuric acid dissolves limestone, right? （来源：TPO16-L2）", "地质化学", "/dɪˈzɑːlv/"],
  ["dissolution", "溶解（名词；化学溶解过程，区别于物理侵蚀）", "The passageways of the cave were created by the chemical dissolution of limestone by sulfuric acid rather than by physical erosion from moving water. （来源：词典风格）", "地质化学", "/ˌdɪs.əˈluː.ʃən/"],
  ["deposit", "沉淀物；沉积（化学反应后留下的固体，如石膏）；存款", "Over millions of years, groundwater left deposits of a mineral called calcite on the rock within Devils Hole. （来源：TPO17-L3）", "地质化学", "/dɪˈpɑː.zɪt/"],
  ["precipitation", "沉淀（化学反应中固体从溶液中析出）；降水", "Water changes back and forth from lakes and oceans to vapor, and then back to water again when it falls as rain or snow—as precipitation. （来源：TPO24-L4）", "地质化学", "/prɪˌsɪp.ɪˈteɪ.ʃən/"],
  ["gypsum", "石膏（硫酸与石灰岩反应生成的矿物，CaSO₄·2H₂O）", "You'll find lots of gypsum deposited at Lechuguilla, and, as we know, gypsum is soluble in water. （来源：TPO16-L2）", "地质化学", "/ˈdʒɪp.səm/"],
  ["anhydrite", "硬石膏（无水硫酸钙 CaSO₄，遇水可转变成石膏）", "Anhydrite is a mineral form of calcium sulfate that contains no water in its crystal structure, and when it comes into contact with water it can convert into gypsum. （来源：词典风格）", "地质化学", "/ænˈhaɪ.draɪt/"],
  ["carbonate", "碳酸盐（含碳酸根 CO₃²⁻ 的矿物类；石灰岩的主要成分是碳酸钙）", "Limestone is composed mainly of calcium carbonate, and it is readily attacked by acids such as carbonic acid and sulfuric acid. （来源：词典风格）", "地质化学", "/ˈkɑːr.bə.nət/"],
  ["calcite", "方解石（石灰岩的主要矿物成分，碳酸钙的晶体形态）", "Over millions of years, groundwater left deposits of a mineral called calcite on the rock within Devils Hole. （来源：TPO17-L3）", "地质化学", "/ˈkæl.saɪt/"],
  ["acidic", "酸性的（pH 值低，有腐蚀性）", "Acidic groundwater, formed when rainwater absorbs carbon dioxide, slowly dissolves limestone and enlarges cracks in the rock. （来源：词典风格）", "地质化学", "/əˈsɪd.ɪk/"],
  ["erosion", "侵蚀（水流、风等对岩石的物理冲刷磨损）", "During the Pleistocene epoch, sediment was made by the kind of erosion and weathering that happens when the climate is colder. （来源：TPO15-L5）", "地质化学", "/ɪˈroʊ.ʒən/"],
  ["groundwater", "地下水（储存在地下岩层空隙中的水）", "Over millions of years, groundwater left deposits of a mineral called calcite on the rock within Devils Hole. （来源：TPO17-L3）", "地质化学", "/ˈɡraʊnd.wɔː.tər/"],
  ["cave", "洞穴（天然形成的可进入的地下空间）", "It's the deepest limestone cave in the U.S. （来源：TPO16-L2）", "地质化学", "/keɪv/"],
  ["cavern", "大洞穴（比 cave 更大、更开阔的洞穴）", "Most people think that there are huge pools of oil sitting around in caverns somewhere under there, but that's really rare. （来源：TPO50-L6）", "地质化学", "/ˈkæv.ərn/"],
  ["formation", "形成（过程）；地层；岩层", "The formations are really something, and there's such a variety there, like nothing anywhere else in the world. （来源：TPO16-L2）", "地质化学", "/fɔːrˈmeɪ.ʃən/"],
  ["speleothem", "洞穴次生矿物沉积物（钟乳石、石笋等的总称）", "Speleothems such as stalactites and stalagmites grow extremely slowly, sometimes only a few millimeters per century, as mineral-rich water drips through a cave. （来源：词典风格）", "地质化学", "/ˈspiː.li.ə.θem/"],
  ["stalactite", "钟乳石（从洞穴顶部向下生长）", "Stalactites hang from the ceiling of a cave and are formed as mineral-laden water drips and leaves behind deposits over long periods of time. （来源：词典风格）", "地质化学", "/stəˈlæk.taɪt/"],
  ["stalagmite", "石笋（从洞穴地面向上生长）", "Stalagmites rise from the floor of a cave where water drips from above and deposits dissolved minerals, building the structure upward over thousands of years. （来源：词典风格）", "地质化学", "/stəˈlæɡ.maɪt/"],
  ["permeable", "可渗透的（水或液体能穿过的）", "Sandstone is highly permeable, allowing water to pass through it easily, whereas clay is almost impermeable. （来源：词典风格）", "地质化学", "/ˈpɝː.mi.ə.bəl/"],
  ["fracture", "裂缝（岩石中的裂纹，水或酸进入的通道）", "Acidic groundwater seeps into fractures in the limestone, and over time the dissolving action widens these cracks into passageways. （来源：词典风格）", "地质化学", "/ˈfræk.tʃər/"],
  ["reaction", "化学反应（物质相互作用生成新物质的过程）", "These bacteria actually combine the hydrogen sulfide with the carbon dioxide, and this chemical reaction is what produces organic material, which is the food for larger organisms. （来源：TPO15-L3）", "地质化学", "/riˈæk.ʃən/"],
  ["by-product", "副产物（主反应之外的次要产物）", "Sulfuric acid reacting with limestone leaves a chemical residue, gypsum, as a by-product of the reaction. （来源：词典风格）", "地质化学", "/ˈbaɪ ˌprɑː.dʌkt/"],
  ["evidence", "证据（支持某种结论的事实或线索）", "In fact, there's no evidence that flowing water has ever gone in or out of the cave. （来源：TPO16-L2）", "地质化学", "/ˈev.ə.dəns/"],
  ["instead of", "而不是（强调不是 A，而是 B；如不是水冲，而是酸溶）", "People began to raise crops and animals for food instead of hunting for them. （来源：TPO20-L3）", "地质化学", "/ɪnˈsted əv/"],
  ["rather than", "而不是（与 instead of 同义，更正式）", "The cumulative effect of clouds is to cool Earth rather than heat it. （来源：TPO23-L3）", "地质化学", "/ˈræð.ər ðæn/"],
  ["Lechuguilla Cave", "莱丘基亚洞穴（美国新墨西哥州，因硫酸溶蚀形成的著名洞穴）", "It's safe to say that it's sulfuric acid, and not moving water, that formed Lechuguilla Cave, and those few other ones like it. （来源：TPO16-L2）", "地质化学", "/ˌletʃ.əˈɡiː.ə keɪv/"],
  ["track meet", "田径运动会（track and field 田径运动的比赛）", "How did your track meet go? \"Great,\" she said, \"I placed first in one race and third in another!\" （来源：TPO15-C1）", "校园场景", "/træk miːt/"],
  ["track", "跑道；田径运动（track and field 田径）", "Think of your brain as a muscle: if you didn't practice regularly with your track team and then tried to squeeze in three weeks' worth of running practice the day before a track meet, you wouldn't perform well in your races. （来源：TPO15-C1）", "校园场景", "/træk/"],
  ["varsity", "校队（代表学校参加正式比赛的队伍）", "She made the varsity soccer team in her sophomore year after months of tryouts. （来源：词典风格）", "校园场景", "/ˈvɑːr.sə.t̬i/"],
  ["intramural", "校内（联赛/活动，不与其他学校比赛）", "Intramural sports are open to all students, not just athletes, and no travel is involved. （来源：词典风格）", "校园场景", "/ˌɪn.trəˈmjʊr.əl/"],
  ["tournament", "锦标赛（多场比赛决出冠军）", "The chess tournament will be held in the student center this weekend. （来源：词典风格）", "校园场景", "/ˈtʊr.nə.mənt/"],
  ["championship", "冠军赛，锦标赛（争夺冠军的比赛）", "The basketball team won the regional championship last year. （来源：词典风格）", "校园场景", "/ˈtʃæm.pi.ən.ʃɪp/"],
  ["coach", "教练（训练和指导运动员的人）", "You'll be meeting with Mark Giddis, he's the swimming instructor; he also coaches the swim team. （来源：TPO11-C1）", "校园场景", "/koʊtʃ/"],
  ["athlete", "运动员（参加体育比赛的人）", "Remember the team members are athletes and students, and they need support beyond the sport itself. （来源：TPO47-L5）", "校园场景", "/ˈæθ.liːt/"],
  ["captain", "队长（运动队或社团的负责人）", "As team captain, she organized the practice sessions and kept everyone motivated. （来源：词典风格）", "校园场景", "/ˈkæp.tən/"],
  ["syllabus", "教学大纲（课程计划，第一节课分发）", "I think my professor really miscalculated; the syllabus was way too ambitious—there are only two weeks of classes left and six books on the syllabus we haven't even touched. （来源：TPO10-C4）", "校园场景", "/ˈsɪl.ə.bəs/"],
  ["prerequisite", "先修课程（选某门课之前必须学过的课）", "Usually the system blocks anyone trying to sign up for a class they shouldn't be taking, who hasn't taken the courses you're required to do first, as prerequisites. （来源：TPO05-C4）", "校园场景", "/ˌpriːˈrek.wə.zɪt/"],
  ["elective", "选修课（可自由选择的课程）", "It used to be that the second semester of International Banking was an elective, but now it says it's a required class. （来源：TPO25-C1）", "校园场景", "/ɪˈlek.tɪv/"],
  ["credit", "学分（完成课程获得的学分）", "You need forty-eight credits in your major field to graduate and at least twenty-four credits at the intermediate level or higher. （来源：TPO08-C1）", "校园场景", "/ˈkred.ɪt/"],
  ["semester / term", "学期（一个学年分成的学期）", "I'm working on my schedule for next term, and I've got room for one more course. （来源：TPO23-C4）", "校园场景", "/səˈmes.tər/"],
  ["major", "专业，主修（学生主要学习的学科）", "I'm planning to take a management course next semester, but I don't know if it'll count toward my major. （来源：TPO25-C1）", "校园场景", "/ˈmeɪ.dʒər/"],
  ["minor", "辅修（次要学习的学科，比 major 课程少）", "A major in aerospace engineering with a minor in math—you'll go far with that degree. （来源：TPO21-C1）", "校园场景", "/ˈmaɪ.nər/"],
  ["advisor", "学业顾问，导师（指导学生选课的老师）", "My advisor suggested economics and accounting, but I'm not really sure about those courses. （来源：TPO21-C4）", "校园场景", "/ədˈvaɪ.zər/"],
  ["office hours", "答疑时间（教授固定时段接待学生）", "If you have any trouble or any more questions, feel free to come by during my office hours. （来源：TPO13-C1）", "校园场景", "/ˈɔː.fɪs ˌaʊrz/"],
  ["registration", "注册，选课（办理入学或选课手续）", "Registration for the spring semester opens next week, so plan your courses early. （来源：词典风格）", "校园场景", "/ˌredʒ.ɪˈstreɪ.ʃən/"],
  ["enroll", "注册，入学（正式加入课程或学校）", "Master Writer's an advanced seminar, so students need to get a strong foundation in literary theory and criticism before I let them enroll. （来源：TPO23-C4）", "校园场景", "/ɪnˈroʊl/"],
  ["transcript", "成绩单（记录课程与成绩的正式文件）", "The graduate school requires an official transcript from your university. （来源：词典风格）", "校园场景", "/ˈtræn.skrɪpt/"],
  ["midterm", "期中考试（学期中期的考试）", "The midterm exam showed me that you know all the details of who, where, and when; for this test, I want to see how you can put it all together to show some original thinking. （来源：TPO16-C4）", "校园场景", "/ˌmɪdˈtɝːm/"],
  ["deadline", "截止日期（必须完成任务的最后期限）", "For course books, the deadline is four weeks after the beginning of the semester. （来源：TPO10-C4）", "校园场景", "/ˈded.laɪn/"],
  ["extension", "延期（延长截止日期）；分机号", "The thing is, I was wondering if there's any way I could get an extension on the paper—I know it's due next week. （来源：TPO49-C4）", "校园场景", "/ɪkˈsten.ʃən/"],
  ["term paper", "学期论文（课程结束时提交的论文）", "We shouldn't wait until the last minute to find an idea and get started working on our term paper. （来源：TPO06-C4）", "校园场景", "/tɝːm ˈpeɪ.pər/"],
  ["thesis", "毕业论文（本科或硕士毕业前撰写的论文）", "I'll have to start writing my thesis, since I'm going for my master's degree. （来源：TPO02-C4）", "校园场景", "/ˈθiː.sɪs/"],
  ["dissertation", "博士论文（获得博士学位必须完成的长篇论文）", "She spent three years conducting fieldwork before she could begin writing her dissertation. （来源：词典风格）", "校园场景", "/ˌdɪs.ərˈteɪ.ʃən/"],
  ["seminar", "研讨课（小班讨论课，学生参与度高）", "I assume you've taken a seminar—yeah, I took the marketing seminar. （来源：TPO25-C1）", "校园场景", "/ˈsem.ə.nɑːr/"],
  ["plagiarism", "抄袭（把别人的作品当作自己的，学术不端）", "Plagiarism can result in failing the course or even expulsion. （来源：词典风格）", "校园场景", "/ˈpleɪ.dʒə.rɪ.zəm/"],
  ["citation", "引用（注明资料来源的引文）", "The Pulitzer Prize Committee gave him a citation in 1984 for his special contribution to the education and enjoyment of America's children and their parents. （来源：TPO43-L5）", "校园场景", "/saɪˈteɪ.ʃən/"],
  ["check out", "借出（从图书馆借书）；结账", "You need to return it today if you want to check out any books today—that's our policy. （来源：TPO20-C1）", "校园场景", "/tʃek aʊt/"],
  ["renew", "续借（延长图书借期）；更新", "If you fill out a form requesting the book back in two weeks, the person who requested it won't be able to renew it, and you'll get it back quickly. （来源：TPO20-C1）", "校园场景", "/rɪˈnuː/"],
  ["overdue", "逾期的（超过还书日期未还）", "The library sent a notice about the overdue books on his account. （来源：词典风格）", "校园场景", "/ˌoʊ.vərˈduː/"],
  ["fine", "罚款（逾期还书的罚款）", "The due date is tomorrow; after that there will be a two dollar per day fine. （来源：TPO20-C1）", "校园场景", "/faɪn/"],
  ["reserve", "保留本（教授指定的参考资料，一般只能在馆内阅读）", "You should ask your professor to put some of the copies on reserve—you know about the reserve system, right? （来源：TPO14-C1）", "校园场景", "/rɪˈzɝːv/"],
  ["periodical", "期刊（定期出版的刊物，如杂志或学报）", "The latest periodicals are displayed on the second floor of the library. （来源：词典风格）", "校园场景", "/ˌpɪr.iˈɑː.dɪ.kəl/"],
  ["journal", "学术期刊（发表专业研究论文的刊物）", "Find three journal articles about this topic, or another topic that interests you, and discuss them. （来源：TPO19-C1）", "校园场景", "/ˈdʒɝː.nəl/"],
  ["interlibrary loan", "馆际互借（从其他图书馆借书的服务）", "We have an interlibrary loan service: if you need to get hold of a book that's not in our library, there's a truck that runs between our library and a few other public and university libraries in this area. （来源：TPO07-C4）", "校园场景", "/ˌɪn.tərˈlaɪ.brer.i loʊn/"],
  ["dormitory / dorm", "宿舍（学生住宿的楼房）", "The books are in my dorm room; I need to head back down to the dorm right now. （来源：TPO20-C1）", "校园场景", "/ˈdɔːr.mə.tɔːr.i/"],
  ["roommate", "室友（同住一个房间的人）", "I've got one roommate who is from the south and another one from New York, and we all talk totally different. （来源：TPO06-C4）", "校园场景", "/ˈruːm.meɪt/"],
  ["dining hall / cafeteria", "食堂，自助餐厅（学生用餐的地方）", "I'm OK with my meal plan; I'm actually here about the food in the student cafeteria. （来源：TPO19-C4）", "校园场景", "/ˈdaɪ.nɪŋ hɔːl/"],
  ["meal plan", "餐饮计划（预付费的包餐制度）", "If it's about your meal plan, you'll need to go to room 45, just down the hall. （来源：TPO19-C4）", "校园场景", "/miːl plæn/"],
  ["orientation", "迎新活动（开学时帮助新生熟悉校园的活动）", "I couldn't come to the student orientation, and I'm wondering if you can give me a few quick pointers about the library. （来源：TPO07-C4）", "校园场景", "/ˌɔːr.i.enˈteɪ.ʃən/"],
  ["extracurricular", "课外的（活动，如社团、体育）", "Extracurricular activities look good on a graduate school application. （来源：词典风格）", "校园场景", "/ˌek.strə.kəˈrɪk.jə.lər/"],
  ["tuition", "学费（上学的费用）", "Graduate school tuition's expensive, and these courses will give you a good overview of the field before committing yourself. （来源：TPO21-C4）", "校园场景", "/tuˈɪʃ.ən/"],
  ["scholarship", "奖学金（根据成绩或才能发放的资助）", "She received a full scholarship to study abroad. （来源：词典风格）", "校园场景", "/ˈskɑː.lɚ.ʃɪp/"],
  ["financial aid", "经济资助（帮助学生的各类资金援助总称）", "They said their remaining positions were for work-study students getting financial aid. （来源：TPO18-C1）", "校园场景", "/faɪˈnæn.ʃəl eɪd/"],
  ["grant", "助学金（通常不需要偿还的资助）", "A panel of professors reviews the applications for the grant, and then they decide which research projects should be funded. （来源：TPO20-C4）", "校园场景", "/ɡrænt/"],
  ["loan", "贷款（需要偿还的借款）", "Our loan period is a month; we also have an interlibrary loan service. （来源：TPO07-C4）", "校园场景", "/loʊn/"],
  ["internship", "实习（学生在工作中获得实践经验）", "The internship at the museum gave her hands-on experience in curation. （来源：词典风格）", "校园场景", "/ˈɪn.tɝːn.ʃɪp/"],
  ["career fair", "招聘会（企业与学生见面的就业活动）", "The career fair is generally an opportunity for local businesses to recruit new employees, and for soon-to-be graduates to have interviews with several companies. （来源：TPO06-C1）", "校园场景", "/kəˈrɪr fer/"],
  ["resume", "简历（求职用的个人经历简介）", "It'd be a good experience for you—you could put it on your resume. （来源：TPO11-C4）", "校园场景", "/ˈrez.ə.meɪ/"],
  ["lease", "租约（租房合同）", "The lease for the apartment runs from September to August, and utilities are separate. （来源：词典风格）", "校园场景", "/liːs/"],
  ["utilities", "水电杂费（水、电、燃气等费用）", "Utilities are not included in the rent, so the total bill is higher. （来源：词典风格）", "校园场景", "/juːˈtɪl.ə.t̬iz/"],
  ["off-campus", "校外的（不住在学校宿舍，在校外租房）", "Between my off-campus address, my e-mail account, and the school newspaper, I don't think there'll be a problem. （来源：TPO45-C1）", "校园场景", "/ɔːf ˈkæm.pəs/"],
  ["commuter", "走读生，通勤者（每天往返学校的人）", "As a commuter, she drives forty minutes to campus each morning. （来源：词典风格）", "校园场景", "/kəˈmjuː.t̬ər/"],
  ["shuttle bus", "校车，班车（校园或校园间的接驳车）", "A free shuttle bus runs between the two campuses every hour. （来源：词典风格）", "校园场景", "/ˈʃʌt.əl bʌs/"],
];
